import { MigrationInterface, QueryRunner } from "typeorm";

export class CreateAutobidTable1728398356220 implements MigrationInterface {
    name = 'CreateAutobidTable1728398356220'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "role_permissions_permission" DROP CONSTRAINT "FK_bfbc9e263d4cea6d7a8c9eb3ad2"`);
        await queryRunner.query(`ALTER TABLE "role_permissions_permission" DROP CONSTRAINT "FK_b36cb2e04bc353ca4ede00d87b9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b36cb2e04bc353ca4ede00d87b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bfbc9e263d4cea6d7a8c9eb3ad"`);
        await queryRunner.query(`ALTER TABLE "national_identity" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "national_identity" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "national_identity" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "company" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "company" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "company" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "user_notification_preference" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "user_notification_preference" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "user_notification_preference" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "review" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "token_confirmation" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "notification" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "listing_attributes" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "listing_attributes" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "listing_attributes" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "chat" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "gps_coordinate" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "gps_coordinate" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "gps_coordinate" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "general_ledger" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "user_tracking" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "admin_default" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "role_permissions_permission" DROP COLUMN "use"`);
        await queryRunner.query(`ALTER TABLE "role_permissions_permission" DROP COLUMN "approve"`);
        await queryRunner.query(`ALTER TABLE "role_permissions_permission" ADD "approve" boolean DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "role_permissions_permission" ADD "use" boolean DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "user" ADD "autoBidEnable" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "auto_bid" ADD "listingId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "auto_bid" ADD "auctionId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "auto_bid" ADD "userId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "review" ALTER COLUMN "updatedAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "offer" ALTER COLUMN "deletedAt" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "offer" ALTER COLUMN "updatedAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "search_history" ALTER COLUMN "deletedAt" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "search_history" ALTER COLUMN "updatedAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "flag_listing" ALTER COLUMN "deletedAt" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "flag_listing" ALTER COLUMN "updatedAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "child_issue" ALTER COLUMN "deletedAt" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "child_issue" ALTER COLUMN "updatedAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "token_confirmation" ALTER COLUMN "updatedAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "notification" ALTER COLUMN "updatedAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "listing_type" ALTER COLUMN "deletedAt" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "listing_type" ALTER COLUMN "updatedAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "attribute_set" ALTER COLUMN "deletedAt" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "attribute_set" ALTER COLUMN "updatedAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "attribute" ALTER COLUMN "deletedAt" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "attribute" ALTER COLUMN "updatedAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "parent_issue" ALTER COLUMN "deletedAt" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "parent_issue" ALTER COLUMN "updatedAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "ticket" ALTER COLUMN "updatedAt" SET DEFAULT '"2024-10-08T14:39:17.553Z"'`);
        await queryRunner.query(`ALTER TABLE "ticket" ALTER COLUMN "deletedAt" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "chat" ALTER COLUMN "updatedAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "messages" ALTER COLUMN "updatedAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "user" ALTER COLUMN "updatedAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "user" ALTER COLUMN "deletedAt" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "auction" ALTER COLUMN "deletedAt" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "auction" ALTER COLUMN "updatedAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "auction_participant" ALTER COLUMN "deletedAt" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "auction_participant" ALTER COLUMN "updatedAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "listing" ALTER COLUMN "deletedAt" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "listing" ALTER COLUMN "updatedAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "wishlist" ALTER COLUMN "deletedAt" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "wishlist" ALTER COLUMN "updatedAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "general_ledger" ALTER COLUMN "updatedAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "response_template" ALTER COLUMN "deletedAt" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "response_template" ALTER COLUMN "updatedAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "user_tracking" ALTER COLUMN "updatedAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "auto_bid" ALTER COLUMN "deletedAt" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "auto_bid" ALTER COLUMN "updatedAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "admin_default" ALTER COLUMN "updatedAt" SET DEFAULT now()`);
        await queryRunner.query(`CREATE INDEX "IDX_b36cb2e04bc353ca4ede00d87b" ON "role_permissions_permission" ("roleId") `);
        await queryRunner.query(`CREATE INDEX "IDX_bfbc9e263d4cea6d7a8c9eb3ad" ON "role_permissions_permission" ("permissionId") `);
        await queryRunner.query(`ALTER TABLE "role_permissions_permission" ADD CONSTRAINT "FK_b36cb2e04bc353ca4ede00d87b9" FOREIGN KEY ("roleId") REFERENCES "role"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions_permission" ADD CONSTRAINT "FK_bfbc9e263d4cea6d7a8c9eb3ad2" FOREIGN KEY ("permissionId") REFERENCES "permission"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "role_permissions_permission" DROP CONSTRAINT "FK_bfbc9e263d4cea6d7a8c9eb3ad2"`);
        await queryRunner.query(`ALTER TABLE "role_permissions_permission" DROP CONSTRAINT "FK_b36cb2e04bc353ca4ede00d87b9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bfbc9e263d4cea6d7a8c9eb3ad"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b36cb2e04bc353ca4ede00d87b"`);
        await queryRunner.query(`ALTER TABLE "admin_default" ALTER COLUMN "updatedAt" SET DEFAULT '2024-10-07 08:10:56.935'`);
        await queryRunner.query(`ALTER TABLE "auto_bid" ALTER COLUMN "updatedAt" SET DEFAULT '2024-10-07 08:10:56.935'`);
        await queryRunner.query(`ALTER TABLE "auto_bid" ALTER COLUMN "deletedAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "user_tracking" ALTER COLUMN "updatedAt" SET DEFAULT '2024-10-07 08:10:56.935'`);
        await queryRunner.query(`ALTER TABLE "response_template" ALTER COLUMN "updatedAt" SET DEFAULT '2024-10-07 08:10:56.935'`);
        await queryRunner.query(`ALTER TABLE "response_template" ALTER COLUMN "deletedAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "general_ledger" ALTER COLUMN "updatedAt" SET DEFAULT '2024-10-07 08:10:56.935'`);
        await queryRunner.query(`ALTER TABLE "wishlist" ALTER COLUMN "updatedAt" SET DEFAULT '2024-10-07 08:10:56.935'`);
        await queryRunner.query(`ALTER TABLE "wishlist" ALTER COLUMN "deletedAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "listing" ALTER COLUMN "updatedAt" SET DEFAULT '2024-10-07 08:10:56.935'`);
        await queryRunner.query(`ALTER TABLE "listing" ALTER COLUMN "deletedAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "auction_participant" ALTER COLUMN "updatedAt" SET DEFAULT '2024-10-07 08:10:56.935'`);
        await queryRunner.query(`ALTER TABLE "auction_participant" ALTER COLUMN "deletedAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "auction" ALTER COLUMN "updatedAt" SET DEFAULT '2024-10-07 08:10:56.935'`);
        await queryRunner.query(`ALTER TABLE "auction" ALTER COLUMN "deletedAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "user" ALTER COLUMN "deletedAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "user" ALTER COLUMN "updatedAt" SET DEFAULT '2024-10-07 08:10:56.935'`);
        await queryRunner.query(`ALTER TABLE "messages" ALTER COLUMN "updatedAt" SET DEFAULT '2024-10-07 08:10:56.935'`);
        await queryRunner.query(`ALTER TABLE "chat" ALTER COLUMN "updatedAt" SET DEFAULT '2024-10-07 08:10:56.935'`);
        await queryRunner.query(`ALTER TABLE "ticket" ALTER COLUMN "deletedAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "ticket" ALTER COLUMN "updatedAt" SET DEFAULT '2024-10-07 08:10:56.935'`);
        await queryRunner.query(`ALTER TABLE "parent_issue" ALTER COLUMN "updatedAt" SET DEFAULT '2024-10-07 08:10:56.935'`);
        await queryRunner.query(`ALTER TABLE "parent_issue" ALTER COLUMN "deletedAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "attribute" ALTER COLUMN "updatedAt" SET DEFAULT '2024-10-07 08:10:56.935'`);
        await queryRunner.query(`ALTER TABLE "attribute" ALTER COLUMN "deletedAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "attribute_set" ALTER COLUMN "updatedAt" SET DEFAULT '2024-10-07 08:10:56.935'`);
        await queryRunner.query(`ALTER TABLE "attribute_set" ALTER COLUMN "deletedAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "listing_type" ALTER COLUMN "updatedAt" SET DEFAULT '2024-10-07 08:10:56.935'`);
        await queryRunner.query(`ALTER TABLE "listing_type" ALTER COLUMN "deletedAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "notification" ALTER COLUMN "updatedAt" SET DEFAULT '2024-10-07 08:10:56.935'`);
        await queryRunner.query(`ALTER TABLE "token_confirmation" ALTER COLUMN "updatedAt" SET DEFAULT '2024-10-07 08:10:56.935'`);
        await queryRunner.query(`ALTER TABLE "child_issue" ALTER COLUMN "updatedAt" SET DEFAULT '2024-10-07 08:10:56.935'`);
        await queryRunner.query(`ALTER TABLE "child_issue" ALTER COLUMN "deletedAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "flag_listing" ALTER COLUMN "updatedAt" SET DEFAULT '2024-10-07 08:10:56.935'`);
        await queryRunner.query(`ALTER TABLE "flag_listing" ALTER COLUMN "deletedAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "search_history" ALTER COLUMN "updatedAt" SET DEFAULT '2024-10-07 08:10:56.935'`);
        await queryRunner.query(`ALTER TABLE "search_history" ALTER COLUMN "deletedAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "offer" ALTER COLUMN "updatedAt" SET DEFAULT '2024-10-07 08:10:56.935'`);
        await queryRunner.query(`ALTER TABLE "offer" ALTER COLUMN "deletedAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "review" ALTER COLUMN "updatedAt" SET DEFAULT '2024-10-07 08:10:56.935'`);
        await queryRunner.query(`ALTER TABLE "auto_bid" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "auto_bid" DROP COLUMN "auctionId"`);
        await queryRunner.query(`ALTER TABLE "auto_bid" DROP COLUMN "listingId"`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "autoBidEnable"`);
        await queryRunner.query(`ALTER TABLE "role_permissions_permission" DROP COLUMN "use"`);
        await queryRunner.query(`ALTER TABLE "role_permissions_permission" DROP COLUMN "approve"`);
        await queryRunner.query(`ALTER TABLE "role_permissions_permission" ADD "approve" boolean DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "role_permissions_permission" ADD "use" boolean DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "admin_default" ADD "deletedAt" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "user_tracking" ADD "deletedAt" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "general_ledger" ADD "deletedAt" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "gps_coordinate" ADD "deletedAt" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "gps_coordinate" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT '2024-10-07 08:10:56.935'`);
        await queryRunner.query(`ALTER TABLE "gps_coordinate" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "messages" ADD "deletedAt" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "chat" ADD "deletedAt" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "listing_attributes" ADD "deletedAt" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "listing_attributes" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT '2024-10-07 08:10:56.935'`);
        await queryRunner.query(`ALTER TABLE "listing_attributes" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "notification" ADD "deletedAt" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "token_confirmation" ADD "deletedAt" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "review" ADD "deletedAt" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "user_notification_preference" ADD "deletedAt" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "user_notification_preference" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT '2024-10-07 08:10:56.935'`);
        await queryRunner.query(`ALTER TABLE "user_notification_preference" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "company" ADD "deletedAt" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "company" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT '2024-10-07 08:10:56.935'`);
        await queryRunner.query(`ALTER TABLE "company" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "national_identity" ADD "deletedAt" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "national_identity" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT '2024-10-07 08:10:56.935'`);
        await queryRunner.query(`ALTER TABLE "national_identity" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`CREATE INDEX "IDX_bfbc9e263d4cea6d7a8c9eb3ad" ON "role_permissions_permission" ("permissionId") `);
        await queryRunner.query(`CREATE INDEX "IDX_b36cb2e04bc353ca4ede00d87b" ON "role_permissions_permission" ("roleId") `);
        await queryRunner.query(`ALTER TABLE "role_permissions_permission" ADD CONSTRAINT "FK_b36cb2e04bc353ca4ede00d87b9" FOREIGN KEY ("roleId") REFERENCES "role"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions_permission" ADD CONSTRAINT "FK_bfbc9e263d4cea6d7a8c9eb3ad2" FOREIGN KEY ("permissionId") REFERENCES "permission"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
