image: node:latest
definitions:
  services:
    postgres:
      image: postgres:latest
      environment:
        POSTGRES_DB: 'waseet'
        POSTGRES_USER: 'waseet'
        POSTGRES_PASSWORD: 'darkNight'

  caches:
    npm: node_modules
    sonar: ~/.sonar
  steps:
    - step: &code-lint
        name: Linting
        runs-on:
          - self.hosted # Runner Label
          - linux # Runner Label
        caches:
          - npm
        script:
          - npm ci

    - step: &owasp-dependency-check
        name: 'OWASP Dependency Check'
        runs-on:
          - self.hosted
          - linux
        script:
          - pipe: docker://aligent/owasp-dependency-check-pipe
            variables:
              SCAN_PATH: './package-lock.json'
              CVSS_FAIL_LEVEL: '1'

    - step: &build
        name: Build
        runs-on:
          - self.hosted
          - linux
        caches:
          - npm
        script:
          - npm ci
          # - npm run test
          - npm run build

    - step: &test
        name: Test
        runs-on:
          - self.hosted
          - linux
        caches:
          - npm
        script:
          - npm ci
          - npm run test
    - step: &validate-db
        name: 'Validate DB Schema'
        runs-on:
          - self.hosted
          - linux
        caches:
          - npm
        services:
          - postgres
        script:
          - export DATABASE_URL=postgres://waseet:darkNight@localhost:5432/waseet
          - npm ci
          - npm run migration:run
          - npm run seed
          # - npm run migration:revert

    - step: &security-checks
        name: Security Checks
        runs-on:
          - self.hosted
          - linux
        caches:
          - npm
        script:
          - npm ci
          # - npm audit

    - step: &sonar-analysis
        name: SonarQube analysis
        runs-on:
          - self.hosted
          - linux
        script:
          - pipe: sonarsource/sonarqube-scan:2.0.1
            variables:
              SONAR_HOST_URL: ${SONAR_HOST_URL}
              SONAR_TOKEN: ${SONAR_TOKEN}

    - step: &push-to-dockerhub
        name: Build and Push to Docker Hub
        runs-on:
          - self.hosted
          - linux
        services:
          - docker
        script:
          - echo $DOCKERHUB_PASSWORD | docker login --username $DOCKERHUB_USERNAME --password-stdin
          - |
            for i in {1..3}; do
              docker build -f Dockerfile -t $DOCKERHUB_USERNAME/$DOCKERHUB_REPO:$BITBUCKET_COMMIT .
              if docker push $DOCKERHUB_USERNAME/$DOCKERHUB_REPO:$BITBUCKET_COMMIT; then
                break
              fi
              echo "Retrying Docker push ($i/3)..."
              sleep 10
            done

    - step: &deploy-to-test
        name: Deploy to CapRover
        deployment: test
        runs-on:
          - self.hosted
          - linux
        services:
          - docker
        image: caprover/cli-caprover:v2.1.1
        script:
          - caprover deploy --caproverUrl $CAPROVER_URL --caproverPassword $CAPROVER_PASSWORD --caproverApp $CAPROVER_APP --imageName "$DOCKERHUB_USERNAME/$DOCKERHUB_REPO:$BITBUCKET_COMMIT"

clone:
  depth: full

pipelines:
  pull-requests:
    '**':
      - step: *code-lint
      - step: *build
      # - step: *test
      # - step: *sonar-analysis
      - step: *validate-db
      - step: *security-checks
      # - step: *owasp-dependency-check

  branches:
    develop:
      - step: *push-to-dockerhub
      - step: *deploy-to-test

options:
  size: 2x
