version: "3.3"

services:
  backend:
    build:
      context: .
      target: builder
    volumes:
      - .:/usr/src/app
      - ./node_modules:/usr/src/app/node_modules
    command: sh -c "npm run start:dev"
    env_file:
      - .env
    ports:
      - ${PORT}:3000 # <host port> : <container port>
    networks:
      - internal

networks:
  internal: