version: "3.3"

services:
  backend:
    build:
      context: .
      target: builder
    volumes:
      - .:/usr/src/app
      - ./node_modules:/usr/src/app/node_modules
    command: sh -c "npm install && npm run seed && npm run migration:run && npm run start:dev"
    env_file:
      - .env
    ports:
      - ${PORT}:3000 # <host port> : <container port>
    networks:
      - app-network
  #
  # Postgres DB
  #
  postgres:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=waseet_db
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - db:/var/lib/postgresql/data
    command: -p ${POSTGRES_PORT}
    networks:
      - app-network

volumes:
  db:

networks:
  app-network:
    driver: bridge