/*
 * Copyright (c) 2024, Waseet LLC. All rights reserved.
 * For license. See license.txt
 */

import { DeepPartial } from 'typeorm';
import { Attribute } from '../../entities';

export const AttributeFactory: DeepPartial<Attribute>[] = [
  {
    id: '6d374d73-161c-49bd-81c6-9f430876b6d6',
    englishName: 'Area',
    arabicName: 'المساحة',
    type: 'Number',
    icon: null,
    dropDownOptions: [],
    isRequired: false,
    showInSummary: true,
    hiddenToBuyers: false,
    isAmenity: false,
    isAddress: false,
    showInComparison: true,
    showInFilters: true,
    filterIndex: 1,
    summaryIndex: 1,
    createListingIndex: 2,
    thiqaIntegration: [],
  },
  {
    id: 'fb9f6f4d-33b5-4355-aec2-3804b29bbb8c',
    englishName: 'Apartment Number',
    arabicName: 'رقم الوحدة السكنية',
    type: 'Address',
    icon: null,
    dropDownOptions: null,
    isRequired: false,
    showInSummary: true,
    hiddenToBuyers: false,
    isAmenity: false,
    isAddress: true,
    showInComparison: false,
    showInFilters: false,
    filterIndex: 1,
    summaryIndex: 6,
    createListingIndex: 6,
    thiqaIntegration: [],
  },
  {
    id: 'fc0fe32f-399b-4285-948f-59d015c5ad1b',
    englishName: 'Number of Storeys',
    arabicName: 'عدد الأدوار',
    type: 'Dropdown',
    icon: null,
    dropDownOptions: [
      '1',
      '2',
      '3',
      '4',
      '5',
      '6',
      '7',
      '8',
      '9',
      '10',
      '11',
      '12',
      '13',
      'More Than 13',
    ],
    isRequired: false,
    showInSummary: true,
    hiddenToBuyers: false,
    isAmenity: false,
    isAddress: false,
    showInComparison: true,
    showInFilters: true,
    filterIndex: 4,
    summaryIndex: 3,
    createListingIndex: 5,
    thiqaIntegration: ['2'],
  },
  {
    id: '49f6e86b-3664-471c-b679-c558a962191b',
    englishName: 'Number of Bathrooms',
    arabicName: 'عدد الحمامات',
    type: 'Dropdown',
    icon: null,
    dropDownOptions: [
      '1',
      '2',
      '3',
      '4',
      '5',
      '6',
      '7',
      '8',
      '9',
      '10',
      '11',
      '12',
      '13',
      'More than 13',
    ],
    isRequired: false,
    showInSummary: true,
    hiddenToBuyers: false,
    isAmenity: false,
    isAddress: false,
    showInComparison: true,
    showInFilters: true,
    filterIndex: 1,
    summaryIndex: 1,
    createListingIndex: 1,
    thiqaIntegration: [],
  },
  {
    id: '7f697cde-7e29-40c9-8b35-822d1914bd32',
    englishName: 'Tennis court',
    arabicName: 'صالة تنس',
    type: null,
    icon: 'https://storage.googleapis.com/waseet-dev/amenities/ph--tennis-ball.png',
    dropDownOptions: null,
    isRequired: false,
    showInSummary: true,
    hiddenToBuyers: false,
    isAmenity: true,
    isAddress: false,
    showInComparison: true,
    showInFilters: false,
    filterIndex: 1,
    summaryIndex: 1,
    createListingIndex: 1,
    thiqaIntegration: ['sting'],
  },
  {
    id: '9e50193a-9f0a-4708-8187-7201c2b8dca2',
    englishName: 'Basketball court',
    arabicName: 'صالة كرة سلة',
    type: null,
    icon: 'https://storage.googleapis.com/waseet-dev/amenities/ph--court-basketball.png',
    dropDownOptions: null,
    isRequired: false,
    showInSummary: true,
    hiddenToBuyers: false,
    isAmenity: true,
    isAddress: false,
    showInComparison: true,
    showInFilters: false,
    filterIndex: 1,
    summaryIndex: 1,
    createListingIndex: 1,
    thiqaIntegration: ['sting'],
  },
  {
    id: 'd7e111ce-5ca5-4277-b5c4-e958a8105607',
    englishName: 'Jacuzzi',
    arabicName: 'جاكوزي',
    type: null,
    icon: 'https://storage.googleapis.com/waseet-dev/amenities/ph--bathtub.png',
    dropDownOptions: null,
    isRequired: false,
    showInSummary: true,
    hiddenToBuyers: false,
    isAmenity: true,
    isAddress: false,
    showInComparison: true,
    showInFilters: false,
    filterIndex: 1,
    summaryIndex: 1,
    createListingIndex: 1,
    thiqaIntegration: ['sting'],
  },
  {
    id: '869934e3-af58-4d68-9567-4698213dd827',
    englishName: 'District',
    arabicName: 'الحي',
    type: 'Address',
    icon: null,
    dropDownOptions: [],
    isRequired: true,
    showInSummary: true,
    hiddenToBuyers: false,
    isAmenity: false,
    isAddress: true,
    showInComparison: true,
    showInFilters: true,
    filterIndex: 3,
    summaryIndex: 3,
    createListingIndex: 3,
    thiqaIntegration: [],
  },
  {
    id: 'a7fddbec-308f-4ea0-a71f-7bba8fd81f0c',
    englishName: 'Parking',
    arabicName: 'جراج سيارة',
    type: null,
    icon: 'https://storage.googleapis.com/waseet-dev/amenities/ph--car-profile.png',
    dropDownOptions: null,
    isRequired: false,
    showInSummary: true,
    hiddenToBuyers: false,
    isAmenity: true,
    isAddress: false,
    showInComparison: true,
    showInFilters: true,
    filterIndex: 1,
    summaryIndex: 1,
    createListingIndex: 1,
    thiqaIntegration: ['sting'],
  },
  {
    id: '5eefb8af-5032-4d27-8edf-0e17f020ce4a',
    englishName: 'Level',
    arabicName: 'الدور',
    type: 'Dropdown',
    icon: null,
    dropDownOptions: [
      '1',
      '2',
      '3',
      '4',
      '5',
      '6',
      '7',
      '8',
      '9',
      '10',
      '11',
      '12',
      '13',
      'More than 13',
    ],
    isRequired: true,
    showInSummary: true,
    hiddenToBuyers: false,
    isAmenity: false,
    isAddress: false,
    showInComparison: true,
    showInFilters: true,
    filterIndex: 3,
    summaryIndex: 8,
    createListingIndex: 8,
    thiqaIntegration: [],
  },
  {
    id: '1243575d-1aaf-42a2-8ef3-3e573537767b',
    englishName: 'Garage Area',
    arabicName: 'منطقة جراج',
    type: null,
    icon: 'https://storage.googleapis.com/waseet-dev/amenities/ph--hamburger.png',
    dropDownOptions: null,
    isRequired: false,
    showInSummary: true,
    hiddenToBuyers: true,
    isAmenity: true,
    isAddress: false,
    showInComparison: true,
    showInFilters: false,
    filterIndex: 1,
    summaryIndex: 1,
    createListingIndex: 1,
    thiqaIntegration: ['sting'],
  },
  {
    id: 'fd662cb6-0dcd-45d5-9ba6-728d2a7d2ed3',
    englishName: 'Pool',
    arabicName: 'حمام سباحة',
    type: null,
    icon: 'https://storage.googleapis.com/waseet-dev/amenities/ph--swimming-pool.png',
    dropDownOptions: null,
    isRequired: false,
    showInSummary: true,
    hiddenToBuyers: false,
    isAmenity: true,
    isAddress: false,
    showInComparison: true,
    showInFilters: true,
    filterIndex: 1,
    summaryIndex: 1,
    createListingIndex: 1,
    thiqaIntegration: ['sting'],
  },
  {
    id: '7611537a-a0e1-4616-b543-c7f2ceef22fc',
    englishName: 'Outdoor kitchen',
    arabicName: 'مطبخ خارجي',
    type: null,
    icon: 'https://storage.googleapis.com/waseet-dev/amenities/ph--cooking-pot.png',
    dropDownOptions: null,
    isRequired: false,
    showInSummary: true,
    hiddenToBuyers: false,
    isAmenity: true,
    isAddress: false,
    showInComparison: true,
    showInFilters: false,
    filterIndex: 1,
    summaryIndex: 1,
    createListingIndex: 1,
    thiqaIntegration: ['sting'],
  },
  {
    id: '22499374-4aea-487b-9de3-db07b7d06904',
    englishName: 'Garden',
    arabicName: 'حديقة',
    type: null,
    icon: 'https://storage.googleapis.com/waseet-dev/amenities/ph--tree.png',
    dropDownOptions: null,
    isRequired: false,
    showInSummary: true,
    hiddenToBuyers: false,
    isAmenity: true,
    isAddress: false,
    showInComparison: true,
    showInFilters: true,
    filterIndex: 1,
    summaryIndex: 1,
    createListingIndex: 1,
    thiqaIntegration: ['sting'],
  },
  {
    id: 'c586747b-a198-4f4a-9638-ed0f0456f129',
    englishName: 'Guest house',
    arabicName: 'منزل ضيوف',
    type: null,
    icon: 'https://storage.googleapis.com/waseet-dev/amenities/ph--house.png',
    dropDownOptions: null,
    isRequired: false,
    showInSummary: true,
    hiddenToBuyers: false,
    isAmenity: true,
    isAddress: false,
    showInComparison: true,
    showInFilters: true,
    filterIndex: 1,
    summaryIndex: 1,
    createListingIndex: 1,
    thiqaIntegration: ['sting'],
  },
  {
    id: 'f76cce1e-df33-49eb-81c8-b6863e6be595',
    englishName: 'Indoor play area',
    arabicName: 'منطقة لعب داخلية',
    type: null,
    icon: 'https://storage.googleapis.com/waseet-dev/amenities/ph--bowling-ball.png',
    dropDownOptions: null,
    isRequired: false,
    showInSummary: true,
    hiddenToBuyers: false,
    isAmenity: true,
    isAddress: false,
    showInComparison: true,
    showInFilters: false,
    filterIndex: 1,
    summaryIndex: 1,
    createListingIndex: 1,
    thiqaIntegration: ['sting'],
  },
  {
    id: '0c8867d9-c289-40f8-97a2-1228b0b76898',
    englishName: 'Wifi',
    arabicName: 'واي فاي',
    type: null,
    icon: 'https://storage.googleapis.com/waseet-dev/amenities/ph--wifi-medium.png',
    dropDownOptions: null,
    isRequired: false,
    showInSummary: true,
    hiddenToBuyers: false,
    isAmenity: true,
    isAddress: false,
    showInComparison: true,
    showInFilters: true,
    filterIndex: 1,
    summaryIndex: 1,
    createListingIndex: 1,
    thiqaIntegration: ['sting'],
  },
  {
    id: 'de9ad0b9-a555-4352-a876-ab0020796a77',
    englishName: 'Elevator',
    arabicName: 'مصعد',
    type: null,
    icon: 'https://storage.googleapis.com/waseet-dev/amenities/ph--elevator-duotone.png',
    dropDownOptions: null,
    isRequired: false,
    showInSummary: true,
    hiddenToBuyers: false,
    isAmenity: true,
    isAddress: false,
    showInComparison: true,
    showInFilters: true,
    filterIndex: 2,
    summaryIndex: 2,
    createListingIndex: 2,
    thiqaIntegration: ['sting'],
  },
  {
    id: 'b9956f0a-32bb-4766-8527-4e4210dc29b8',
    englishName: 'Maids room',
    arabicName: 'غرفة خادمة',
    type: null,
    icon: 'https://storage.googleapis.com/waseet-dev/amenities/ph--broom.png',
    dropDownOptions: null,
    isRequired: false,
    showInSummary: true,
    hiddenToBuyers: false,
    isAmenity: true,
    isAddress: false,
    showInComparison: true,
    showInFilters: true,
    filterIndex: 1,
    summaryIndex: 1,
    createListingIndex: 1,
    thiqaIntegration: ['sting'],
  },
  {
    id: '15bcb558-ae9e-4ff5-88e3-d3ddd348d47b',
    englishName: 'Pets allowed',
    arabicName: 'مسموح للحيوانات',
    type: null,
    icon: 'https://storage.googleapis.com/waseet-dev/amenities/ph--dog.png',
    dropDownOptions: null,
    isRequired: false,
    showInSummary: true,
    hiddenToBuyers: false,
    isAmenity: true,
    isAddress: false,
    showInComparison: true,
    showInFilters: true,
    filterIndex: 1,
    summaryIndex: 1,
    createListingIndex: 1,
    thiqaIntegration: ['sting'],
  },
  {
    id: '2482de90-a519-4ed2-a8b8-3d494b23f304',
    englishName: 'Balcony',
    arabicName: 'بالكونة',
    type: null,
    icon: 'https://storage.googleapis.com/waseet-dev/amenities/ph--bird.png',
    dropDownOptions: null,
    isRequired: false,
    showInSummary: true,
    hiddenToBuyers: false,
    isAmenity: true,
    isAddress: false,
    showInComparison: true,
    showInFilters: false,
    filterIndex: 1,
    summaryIndex: 1,
    createListingIndex: 1,
    thiqaIntegration: ['sting'],
  },
  {
    id: 'd20b2c0d-493b-4ec2-a02c-e08a03036e47',
    englishName: 'Gym',
    arabicName: 'صالة رياضية',
    type: null,
    icon: 'https://storage.googleapis.com/waseet-dev/amenities/ph--barbell.png',
    dropDownOptions: null,
    isRequired: false,
    showInSummary: true,
    hiddenToBuyers: false,
    isAmenity: true,
    isAddress: false,
    showInComparison: true,
    showInFilters: true,
    filterIndex: 1,
    summaryIndex: 1,
    createListingIndex: 1,
    thiqaIntegration: ['sting'],
  },
  {
    id: '44a5dc5b-fcf8-4a5d-ae84-fc8624d2e433',
    englishName: 'Playground',
    arabicName: 'منطقة رياضية',
    type: null,
    icon: 'https://storage.googleapis.com/waseet-dev/amenities/ph--court-basketball.png',
    dropDownOptions: null,
    isRequired: false,
    showInSummary: true,
    hiddenToBuyers: false,
    isAmenity: true,
    isAddress: false,
    showInComparison: true,
    showInFilters: false,
    filterIndex: 1,
    summaryIndex: 1,
    createListingIndex: 1,
    thiqaIntegration: ['sting'],
  },
  {
    id: 'c96e494f-27b5-45d6-938a-37b3871bb7a3',
    englishName: 'Security',
    arabicName: 'تأمين',
    type: null,
    icon: 'https://storage.googleapis.com/waseet-dev/amenities/ph--security-camera.png',
    dropDownOptions: null,
    isRequired: false,
    showInSummary: true,
    hiddenToBuyers: false,
    isAmenity: true,
    isAddress: false,
    showInComparison: true,
    showInFilters: true,
    filterIndex: 1,
    summaryIndex: 1,
    createListingIndex: 1,
    thiqaIntegration: ['sting'],
  },
  {
    id: '8354be17-fa2f-4f14-afa2-1e2991adc480',
    englishName: 'Air conditioning',
    arabicName: 'تكييف هواء',
    type: null,
    icon: 'https://storage.googleapis.com/waseet-dev/37923833-main logo.svg',
    dropDownOptions: null,
    isRequired: false,
    showInSummary: true,
    hiddenToBuyers: false,
    isAmenity: true,
    isAddress: false,
    showInComparison: true,
    showInFilters: true,
    filterIndex: 1,
    summaryIndex: 1,
    createListingIndex: 1,
    thiqaIntegration: ['sting'],
  },
  {
    id: '790b0f3c-4a60-44d9-9519-9dd41be32461',
    englishName: 'Storage room',
    arabicName: 'غرفة تخزين',
    type: null,
    icon: 'https://storage.googleapis.com/waseet-dev/amenities/ph--warehouse.png',
    dropDownOptions: null,
    isRequired: false,
    showInSummary: true,
    hiddenToBuyers: false,
    isAmenity: true,
    isAddress: false,
    showInComparison: true,
    showInFilters: false,
    filterIndex: 1,
    summaryIndex: 1,
    createListingIndex: 1,
    thiqaIntegration: ['sting'],
  },
  {
    id: '351e0aa3-6bbe-41f8-a92f-0321ceb31c5e',
    englishName: 'Laundry room',
    arabicName: 'غرفة غسيل',
    type: null,
    icon: 'https://storage.googleapis.com/waseet-dev/amenities/ph--washing-machine.png',
    dropDownOptions: null,
    isRequired: false,
    showInSummary: true,
    hiddenToBuyers: false,
    isAmenity: true,
    isAddress: false,
    showInComparison: true,
    showInFilters: false,
    filterIndex: 1,
    summaryIndex: 1,
    createListingIndex: 1,
    thiqaIntegration: ['sting'],
  },
  {
    id: '20511477-b781-42d2-b2a6-83a25f5a0cd0',
    englishName: 'Conference room',
    arabicName: 'غرفة اجتماعات',
    type: null,
    icon: 'https://storage.googleapis.com/waseet-dev/amenities/ph--microphone-stage.png',
    dropDownOptions: null,
    isRequired: false,
    showInSummary: true,
    hiddenToBuyers: false,
    isAmenity: true,
    isAddress: false,
    showInComparison: true,
    showInFilters: false,
    filterIndex: 1,
    summaryIndex: 1,
    createListingIndex: 1,
    thiqaIntegration: ['sting'],
  },
  {
    id: '3eed7a0a-9a74-438c-8b31-5df544573f9f',
    englishName: 'Gated community',
    arabicName: 'مجمع سكني',
    type: null,
    icon: 'https://storage.googleapis.com/waseet-dev/amenities/ph--wall.png',
    dropDownOptions: null,
    isRequired: false,
    showInSummary: true,
    hiddenToBuyers: false,
    isAmenity: true,
    isAddress: false,
    showInComparison: true,
    showInFilters: true,
    filterIndex: 1,
    summaryIndex: 1,
    createListingIndex: 1,
    thiqaIntegration: ['sting'],
  },
  {
    id: 'e9a1f2cd-feb6-4ba5-bca6-b8ced289e01e',
    englishName: 'Covered parking',
    arabicName: 'جراج مغطى',
    type: null,
    icon: 'https://storage.googleapis.com/waseet-dev/amenities/ph--car-simple.png',
    dropDownOptions: null,
    isRequired: false,
    showInSummary: true,
    hiddenToBuyers: false,
    isAmenity: true,
    isAddress: false,
    showInComparison: true,
    showInFilters: false,
    filterIndex: 1,
    summaryIndex: 1,
    createListingIndex: 1,
    thiqaIntegration: ['sting'],
  },
  {
    id: 'b74cfada-0e43-4648-b2d2-65edd6ee8c3e',
    englishName: 'BBQ area',
    arabicName: 'منطقة شواء',
    type: 'String',
    icon: 'https://storage.googleapis.com/waseet-dev/amenities/ph--hamburger.png',
    dropDownOptions: [],
    isRequired: false,
    showInSummary: true,
    hiddenToBuyers: false,
    isAmenity: true,
    isAddress: false,
    showInComparison: true,
    showInFilters: true,
    filterIndex: 1,
    summaryIndex: 1,
    createListingIndex: 1,
    thiqaIntegration: [],
  },
  {
    id: 'f1a2c35f-5f02-4494-9c96-b2ae9cce30ea',
    englishName: 'Rented apartments',
    arabicName: 'الوحدات المؤجرة',
    type: 'Number',
    icon: 'https://storage.googleapis.com/waseet-dev/32733890-image (1).png',
    dropDownOptions: null,
    isRequired: true,
    showInSummary: true,
    hiddenToBuyers: false,
    isAmenity: false,
    isAddress: false,
    showInComparison: true,
    showInFilters: false,
    filterIndex: 3,
    summaryIndex: 3,
    createListingIndex: 3,
    thiqaIntegration: ['sting'],
  },
  {
    id: '0b7f502b-08b5-4b73-bf77-6760ac838ee2',
    englishName: 'Bathrooms per apartment',
    arabicName: 'عدد الحمامات لكل دور',
    type: 'Number',
    icon: 'https://storage.googleapis.com/waseet-dev/71372067-collabo.png',
    dropDownOptions: null,
    isRequired: true,
    showInSummary: true,
    hiddenToBuyers: false,
    isAmenity: false,
    isAddress: false,
    showInComparison: true,
    showInFilters: false,
    filterIndex: 1,
    summaryIndex: 2,
    createListingIndex: 3,
    thiqaIntegration: ['sting'],
  },
  {
    id: '8a9ceb77-86ed-4473-9542-cf7f351110fe',
    englishName: 'Rooms per apartment',
    arabicName: 'عدد الغرف لكل وحدة',
    type: 'Number',
    icon: 'https://storage.googleapis.com/waseet-dev/49306323-api.png',
    dropDownOptions: null,
    isRequired: true,
    showInSummary: true,
    hiddenToBuyers: false,
    isAmenity: false,
    isAddress: false,
    showInComparison: true,
    showInFilters: false,
    filterIndex: 1,
    summaryIndex: 2,
    createListingIndex: 3,
    thiqaIntegration: ['sting'],
  },
  {
    id: 'ea6d09fc-6474-42e1-9aab-0e3e5c417408',
    englishName: 'Street',
    arabicName: 'الشارع',
    type: 'Media',
    icon: 'https://storage.googleapis.com/waseet-dev/53048302-Screenshot from 2024-11-13 14-24-07.png',
    dropDownOptions: null,
    isRequired: true,
    showInSummary: true,
    hiddenToBuyers: false,
    isAmenity: false,
    isAddress: true,
    showInComparison: true,
    showInFilters: false,
    filterIndex: 4,
    summaryIndex: 4,
    createListingIndex: 4,
    thiqaIntegration: ['sting'],
  },
  {
    id: 'ade40c07-5d0f-4398-a9f6-b2e0f5473d7e',
    englishName: 'Country',
    arabicName: 'الدولة',
    type: 'Media',
    icon: 'https://storage.googleapis.com/waseet-dev/70887549-compute.png',
    dropDownOptions: null,
    isRequired: true,
    showInSummary: true,
    hiddenToBuyers: false,
    isAmenity: false,
    isAddress: true,
    showInComparison: true,
    showInFilters: false,
    filterIndex: 1,
    summaryIndex: 1,
    createListingIndex: 1,
    thiqaIntegration: ['sting'],
  },
  {
    id: 'bf1f300c-0c0e-41d7-a18d-359edfd5df2d',
    englishName: 'Number of Rooms',
    arabicName: 'عدد الغرف',
    type: 'Dropdown',
    icon: 'https://storage.googleapis.com/waseet-dev/32991621-collabo.png',
    dropDownOptions: [
      '1',
      '2',
      '3',
      '4',
      '5',
      '6',
      '7',
      '8',
      '9',
      '10',
      '11',
      '12',
      '13',
      'More than 13',
    ],
    isRequired: true,
    showInSummary: true,
    hiddenToBuyers: false,
    isAmenity: false,
    isAddress: false,
    showInComparison: true,
    showInFilters: true,
    filterIndex: 2,
    summaryIndex: 2,
    createListingIndex: 2,
    thiqaIntegration: [],
  },
  {
    id: 'f0b276e4-7c2d-4b83-9ba7-6e7e0e78a182',
    englishName: 'Number of Appartments',
    arabicName: 'عدد الوحدات',
    type: 'Number',
    icon: 'https://storage.googleapis.com/waseet-dev/68857350-image.png',
    dropDownOptions: null,
    isRequired: true,
    showInSummary: true,
    hiddenToBuyers: false,
    isAmenity: false,
    isAddress: false,
    showInComparison: true,
    showInFilters: false,
    filterIndex: 1,
    summaryIndex: 2,
    createListingIndex: 3,
    thiqaIntegration: ['sting'],
  },
  {
    id: '8a68332d-f018-44b9-98c9-44be6c389e1a',
    englishName: 'Area per apartment',
    arabicName: 'مساحة كل وحدة',
    type: 'Number',
    icon: 'https://storage.googleapis.com/waseet-dev/51436985-api.png',
    dropDownOptions: null,
    isRequired: false,
    showInSummary: true,
    hiddenToBuyers: false,
    isAmenity: false,
    isAddress: false,
    showInComparison: true,
    showInFilters: false,
    filterIndex: 1,
    summaryIndex: 2,
    createListingIndex: 2,
    thiqaIntegration: ['sting'],
  },
  {
    id: 'd7f1dc87-7669-493f-ac5b-95ec7c1867cd',
    englishName: 'Boom',
    arabicName: 'Bllom',
    type: 'Number',
    icon: null,
    dropDownOptions: [],
    isRequired: false,
    showInSummary: false,
    hiddenToBuyers: true,
    isAmenity: true,
    isAddress: true,
    showInComparison: true,
    showInFilters: true,
    filterIndex: 2,
    summaryIndex: 2,
    createListingIndex: 2,
    thiqaIntegration: [],
  },
  {
    id: '32fe0fc6-1897-4936-9b72-b1d0de590d22',
    englishName: 'City',
    arabicName: 'المدينة',
    type: 'Media',
    icon: 'https://storage.googleapis.com/waseet-dev/95384642-api.png',
    dropDownOptions: null,
    isRequired: true,
    showInSummary: true,
    hiddenToBuyers: false,
    isAmenity: false,
    isAddress: true,
    showInComparison: true,
    showInFilters: false,
    filterIndex: 2,
    summaryIndex: 2,
    createListingIndex: 2,
    thiqaIntegration: ['sting'],
  },
  {
    id: '6dc31e4c-d478-4c4a-bdd6-584bc30c4a28',
    englishName: 'Building No',
    arabicName: 'رقم المبنى',
    type: 'Address',
    icon: 'https://storage.googleapis.com/waseet-dev/75038896-Screenshot from 2024-11-13 14-24-07.png',
    dropDownOptions: null,
    isRequired: false,
    showInSummary: true,
    hiddenToBuyers: false,
    isAmenity: false,
    isAddress: true,
    showInComparison: false,
    showInFilters: false,
    filterIndex: 5,
    summaryIndex: 5,
    createListingIndex: 5,
    thiqaIntegration: [],
  },
  {
    id: 'e5ae66a1-4908-4c19-9f8f-8608bb02cb20',
    englishName: 'Not seen',
    arabicName: 'Not seen',
    type: 'Number',
    icon: null,
    dropDownOptions: [],
    isRequired: false,
    showInSummary: false,
    hiddenToBuyers: true,
    isAmenity: false,
    isAddress: false,
    showInComparison: false,
    showInFilters: true,
    filterIndex: 1,
    summaryIndex: 1,
    createListingIndex: 1,
    thiqaIntegration: [],
  },
  {
    id: '55cdb0aa-4857-46a5-85dd-41e70e92128e',
    englishName: 'testing atribute',
    arabicName: 'اختباري',
    type: 'Dropdown',
    icon: 'https://storage.googleapis.com/waseet-dev/80371427-black logo copy.svg',
    dropDownOptions: ['option 1 ', '23423', '345'],
    isRequired: true,
    showInSummary: true,
    hiddenToBuyers: false,
    isAmenity: false,
    isAddress: false,
    showInComparison: true,
    showInFilters: true,
    filterIndex: 1,
    summaryIndex: 1,
    createListingIndex: 1,
    thiqaIntegration: [],
  },
  {
    id: '3e537961-f7cd-4a2e-9c65-43a533223b93',
    englishName: 'Test 1',
    arabicName: 'تجريبي 1',
    type: 'Dropdown',
    icon: null,
    dropDownOptions: [],
    isRequired: false,
    showInSummary: false,
    hiddenToBuyers: false,
    isAmenity: true,
    isAddress: false,
    showInComparison: false,
    showInFilters: true,
    filterIndex: 1,
    summaryIndex: 1,
    createListingIndex: 1,
    thiqaIntegration: [],
  },
  {
    id: '4bb4ea98-807f-45a4-9140-e838391d0e9a',
    englishName: 'waseet attribute',
    arabicName: 'وسيط',
    type: 'Dropdown',
    icon: 'https://storage.googleapis.com/waseet-dev/37997264-black logo copy.svg',
    dropDownOptions: ['option 1', 'option 2', 'option 3'],
    isRequired: true,
    showInSummary: true,
    hiddenToBuyers: false,
    isAmenity: false,
    isAddress: false,
    showInComparison: true,
    showInFilters: true,
    filterIndex: 1,
    summaryIndex: 1,
    createListingIndex: 1,
    thiqaIntegration: [],
  },
  {
    id: '315d5919-08dd-4eba-8567-2e00db28c8ca',
    englishName: 'test',
    arabicName: 'wew',
    type: 'Dropdown',
    icon: null,
    dropDownOptions: ['test 1', 'test 2', 'test 3'],
    isRequired: true,
    showInSummary: false,
    hiddenToBuyers: false,
    isAmenity: false,
    isAddress: false,
    showInComparison: false,
    showInFilters: false,
    filterIndex: 1,
    summaryIndex: 1,
    createListingIndex: 1,
    thiqaIntegration: [],
  },
  {
    id: '77bd677c-b55f-47d2-845c-c55bfe57efab',
    englishName: 'testing tuesday',
    arabicName: 'الثلاث اختبار',
    type: 'Dropdown',
    icon: 'https://storage.googleapis.com/waseet-dev/28245171-main logo.svg',
    dropDownOptions: ['Option 1 ', 'Option 2', 'Otion 3', 'option 4'],
    isRequired: true,
    showInSummary: true,
    hiddenToBuyers: false,
    isAmenity: false,
    isAddress: false,
    showInComparison: true,
    showInFilters: true,
    filterIndex: 1,
    summaryIndex: 1,
    createListingIndex: 1,
    thiqaIntegration: [],
  },
  {
    id: '2890cabc-73a2-467d-ae37-d682928f5f16',
    englishName: 'amenity test',
    arabicName: 'اختبار',
    type: 'String',
    icon: 'https://storage.googleapis.com/waseet-dev/36480952-main logo.svg',
    dropDownOptions: null,
    isRequired: false,
    showInSummary: true,
    hiddenToBuyers: false,
    isAmenity: true,
    isAddress: false,
    showInComparison: true,
    showInFilters: true,
    filterIndex: 1,
    summaryIndex: 1,
    createListingIndex: 1,
    thiqaIntegration: [],
  },
  {
    id: 'c247c2f6-8e86-41bf-8aa3-4676399eeb91',
    englishName: 'date testing',
    arabicName: 'اختبار تاريخ',
    type: 'Date',
    icon: null,
    dropDownOptions: null,
    isRequired: true,
    showInSummary: false,
    hiddenToBuyers: false,
    isAmenity: false,
    isAddress: false,
    showInComparison: false,
    showInFilters: false,
    filterIndex: 1,
    summaryIndex: 1,
    createListingIndex: 1,
    thiqaIntegration: [],
  },
  {
    id: '42e71c81-e0f6-4f0b-bd5a-9a3e801c307d',
    englishName: 'Test Att',
    arabicName: 'اختباري',
    type: 'Dropdown',
    icon: null,
    dropDownOptions: ['option 4', 'option 3'],
    isRequired: false,
    showInSummary: true,
    hiddenToBuyers: false,
    isAmenity: false,
    isAddress: false,
    showInComparison: true,
    showInFilters: true,
    filterIndex: 1,
    summaryIndex: 1,
    createListingIndex: 1,
    thiqaIntegration: [],
  },
  {
    id: '90791fce-ab31-45ab-9466-0b633a651cb3',
    englishName: 'Friday',
    arabicName: 'الجمعة',
    type: 'String',
    icon: 'https://storage.googleapis.com/waseet-dev/55795081-main logo.png',
    dropDownOptions: [],
    isRequired: false,
    showInSummary: true,
    hiddenToBuyers: false,
    isAmenity: true,
    isAddress: false,
    showInComparison: true,
    showInFilters: false,
    filterIndex: 1,
    summaryIndex: 1,
    createListingIndex: 1,
    thiqaIntegration: [],
  },
];
