/*
 * Copyright (c) 2024, Waseet LLC. All rights reserved.
 * For license. See license.txt
 */

import { DeepPartial } from 'typeorm';
import { Attribute } from '../../entities';

export const AttributeFactory: DeepPartial<Attribute>[] = [
  {
    englishName: 'Title',
    type: '',
    showInFilters: false,
    showInComparison: true,
    showInSummary: true,
    isRequired: true,
    hiddenToBuyers: false,
    isAmenity: false,
    isAddress: false,
  },

  {
    englishName: 'Address',
    type: '',
    showInFilters: false,
    showInComparison: true,
    showInSummary: true,
    isRequired: true,
    hiddenToBuyers: false,
    isAmenity: false,
    isAddress: false,
  },

  {
    englishName: 'Purpose',
    type: '',
    showInFilters: true,
    showInComparison: true,
    showInSummary: true,
    isRequired: true,
    hiddenToBuyers: false,
    isAmenity: false,
    isAddress: false,
  },
  {
    englishName: 'Image',
    type: '',
    showInFilters: false,
    showInComparison: true,
    showInSummary: true,
    isRequired: true,
    hiddenToBuyers: false,
    isAmenity: false,
    isAddress: false,
  },
  {
    englishName: 'Deed number',
    type: 'number',
    showInFilters: false,
    showInComparison: false,
    showInSummary: false,
    isRequired: true,
    hiddenToBuyers: true,
    isAmenity: false,
    isAddress: false,
  },

  {
    englishName: 'Price',
    type: 'number',
    showInFilters: true,
    showInComparison: true,
    showInSummary: true,
    isRequired: true,
    hiddenToBuyers: false,
    isAmenity: false,
    isAddress: false,
  },

  {
    englishName: 'Area',
    type: 'number',
    showInFilters: true,
    showInComparison: true,
    showInSummary: true,
    isRequired: true,
    hiddenToBuyers: false,
    isAmenity: false,
    isAddress: false,
  },

  {
    englishName: 'City',
    type: 'Address',
    showInFilters: true,
    showInComparison: true,
    showInSummary: true,
    isRequired: true,
    hiddenToBuyers: false,
    isAmenity: false,
    isAddress: true,
  },

  {
    englishName: 'Country',
    type: 'Address',
    showInFilters: true,
    showInComparison: true,
    showInSummary: true,
    isRequired: true,
    hiddenToBuyers: false,
    isAmenity: false,
    isAddress: true,
  },

  {
    englishName: 'District',
    type: 'Address',
    showInFilters: true,
    showInComparison: true,
    showInSummary: true,
    isRequired: true,
    hiddenToBuyers: false,
    isAmenity: false,
    isAddress: true,
  },

  {
    englishName: 'Street',
    type: 'Address',
    showInFilters: true,
    showInComparison: true,
    showInSummary: true,
    isRequired: true,
    hiddenToBuyers: false,
    isAmenity: false,
    isAddress: true,
  },

  {
    englishName: 'Geolocation',
    type: '',
    showInFilters: false,
    showInComparison: false,
    showInSummary: true,
    isRequired: true,
    hiddenToBuyers: false,
    isAmenity: false,
    isAddress: false,
  },

  {
    englishName: 'Property number',
    type: 'number',
    showInFilters: false,
    showInComparison: false,
    showInSummary: false,
    isRequired: true,
    hiddenToBuyers: true,
    isAmenity: false,
    isAddress: false,
  },

  {
    englishName: 'Number of Bathrooms',
    type: 'number',
    showInFilters: true,
    showInComparison: true,
    showInSummary: true,
    isRequired: true,
    hiddenToBuyers: false,
    isAmenity: false,
    isAddress: false,
    dropDownOptions: [
      '1',
      '2',
      '3',
      '4',
      '5',
      '6',
      '7',
      '8',
      '9',
      '10',
      '11',
      '12',
      '13',
      'More than 13',
    ],
  },

  {
    englishName: 'Number of Rooms',
    type: 'number',
    showInFilters: false,
    showInComparison: true,
    showInSummary: true,
    isRequired: true,
    hiddenToBuyers: false,
    isAmenity: false,
    isAddress: false,
    dropDownOptions: [
      '1',
      '2',
      '3',
      '4',
      '5',
      '6',
      '7',
      '8',
      '9',
      '10',
      '11',
      '12',
      '13',
      'More than 13',
    ],
  },

  {
    englishName: 'Level',
    type: 'number',
    showInFilters: true,
    showInComparison: true,
    showInSummary: true,
    isRequired: true,
    hiddenToBuyers: false,
    isAmenity: false,
    isAddress: false,
  },

  {
    englishName: 'Area',
    type: 'number',
    showInFilters: true,
    showInComparison: true,
    showInSummary: true,
    isRequired: true,
    hiddenToBuyers: false,
    isAmenity: false,
    isAddress: false,
  },

  {
    englishName: 'Level',
    type: 'number',
    showInFilters: true,
    showInComparison: true,
    showInSummary: true,
    isRequired: true,
    hiddenToBuyers: false,
    isAmenity: false,
    isAddress: false,
  },
  {
    englishName: 'Rented apartments',
    type: 'number',
    showInFilters: false,
    showInComparison: true,
    showInSummary: true,
    isRequired: true,
    hiddenToBuyers: false,
    isAmenity: false,
    isAddress: false,
    dropDownOptions: [
      '1',
      '2',
      '3',
      '4',
      '5',
      '6',
      '7',
      '8',
      '9',
      '10',
      '11',
      '12',
      '13',
      'More than 13',
    ],
  },

  {
    englishName: 'Number of Storeys',
    type: 'number',
    showInFilters: true,
    showInComparison: true,
    showInSummary: true,
    isRequired: true,
    hiddenToBuyers: false,
    isAmenity: false,
    isAddress: false,
    dropDownOptions: [
      '1',
      '2',
      '3',
      '4',
      '5',
      '6',
      '7',
      '8',
      '9',
      '10',
      '11',
      '12',
      '13',
      'More than 13',
    ],
  },

  {
    englishName: 'Number of Appartments',
    type: 'number',
    showInFilters: false,
    showInComparison: true,
    showInSummary: true,
    isRequired: false,
    hiddenToBuyers: false,
    isAmenity: false,
    isAddress: false,
    dropDownOptions: [
      '1',
      '2',
      '3',
      '4',
      '5',
      '6',
      '7',
      '8',
      '9',
      '10',
      '11',
      '12',
      '13',
      'More than 13',
    ],
  },

  {
    englishName: 'Bathrooms per apartment',
    type: 'number',
    showInFilters: false,
    showInComparison: true,
    showInSummary: true,
    isRequired: false,
    hiddenToBuyers: false,
    isAmenity: false,
    isAddress: false,
    dropDownOptions: [
      '1',
      '2',
      '3',
      '4',
      '5',
      '6',
      '7',
      '8',
      '9',
      '10',
      '11',
      '12',
      '13',
      'More than 13',
    ],
  },

  {
    englishName: 'Bathrooms per apartment',
    type: 'number',
    showInFilters: false,
    showInComparison: true,
    showInSummary: true,
    isRequired: false,
    hiddenToBuyers: false,
    isAmenity: false,
    isAddress: false,
    dropDownOptions: [
      '1',
      '2',
      '3',
      '4',
      '5',
      '6',
      '7',
      '8',
      '9',
      '10',
      '11',
      '12',
      '13',
      'More than 13',
    ],
  },

  {
    englishName: 'Rooms per apartment',
    type: 'number',
    showInFilters: false,
    showInComparison: true,
    showInSummary: true,
    isRequired: false,
    hiddenToBuyers: false,
    isAmenity: false,
    isAddress: false,
    dropDownOptions: [
      '1',
      '2',
      '3',
      '4',
      '5',
      '6',
      '7',
      '8',
      '9',
      '10',
      '11',
      '12',
      '13',
      'More than 13',
    ],
  },

  {
    englishName: 'Area per apartment',
    type: 'number',
    showInFilters: false,
    showInComparison: true,
    showInSummary: true,
    isRequired: false,
    hiddenToBuyers: false,
    isAmenity: false,
    isAddress: false,
    dropDownOptions: [
      '1',
      '2',
      '3',
      '4',
      '5',
      '6',
      '7',
      '8',
      '9',
      '10',
      '11',
      '12',
      '13',
      'More than 13',
    ],
  },

  /////////////////////////////////////////////
  //////////////////////////////////////////////

  //////////////////////////////////////////////////

  {
    englishName: 'Address',
    type: '',
    showInFilters: false,
    showInComparison: true,
    showInSummary: true,
    isRequired: true,
    hiddenToBuyers: false,
    isAmenity: false,
    isAddress: false,
  },
  {
    englishName: 'Purpose',
    type: '',
    showInFilters: true,
    showInComparison: true,
    showInSummary: true,
    isRequired: true,
    hiddenToBuyers: false,
    isAmenity: false,
    isAddress: false,
  },
  {
    englishName: 'Images',
    type: 'media',
    showInFilters: false,
    showInComparison: true,
    showInSummary: true,
    isRequired: true,
    hiddenToBuyers: false,
    isAmenity: false,
    isAddress: false,
  },

  {
    englishName: 'Number of Apartments',
    type: 'number',
    showInFilters: false,
    showInComparison: true,
    showInSummary: true,
    isRequired: true,
    hiddenToBuyers: false,
    isAmenity: false,
    isAddress: false,
    dropDownOptions: [
      '1',
      '2',
      '3',
      '4',
      '5',
      '6',
      '7',
      '8',
      '9',
      '10',
      '11',
      '12',
      '13',
      'More than 13',
    ],
  },

  {
    englishName: 'Garage Area',
    icon: 'https://storage.googleapis.com/waseet-dev/amenities/ph--hamburger.png',
    isRequired: false,
    showInSummary: true,
    hiddenToBuyers: true,
    isAmenity: true,
    showInComparison: true,
    showInFilters: false,
  },

  {
    englishName: 'Pool',
    icon: 'https://storage.googleapis.com/waseet-dev/amenities/ph--swimming-pool.png',
    isRequired: false,
    showInSummary: true,
    hiddenToBuyers: false,
    isAmenity: true,
    showInComparison: true,
    showInFilters: true,
  },
  {
    englishName: 'Outdoor kitchen',
    icon: 'https://storage.googleapis.com/waseet-dev/amenities/ph--cooking-pot.png',
    isRequired: false,
    showInSummary: true,
    hiddenToBuyers: false,
    isAmenity: true,
    showInComparison: true,
    showInFilters: false,
  },

  {
    englishName: 'Garden',
    icon: 'https://storage.googleapis.com/waseet-dev/amenities/ph--tree.png',
    isRequired: false,
    showInSummary: true,
    hiddenToBuyers: false,
    isAmenity: true,
    showInComparison: true,
    showInFilters: true,
  },

  {
    englishName: 'Guest house',
    icon: 'https://storage.googleapis.com/waseet-dev/amenities/ph--house.png',
    isRequired: false,
    showInSummary: true,
    hiddenToBuyers: false,
    isAmenity: true,
    showInComparison: true,
    showInFilters: true,
  },

  {
    englishName: 'Tennis court',
    icon: 'https://storage.googleapis.com/waseet-dev/amenities/ph--tennis-ball.png',
    isRequired: false,
    showInSummary: true,
    hiddenToBuyers: false,
    isAmenity: true,
    showInComparison: true,
    showInFilters: false,
  },
  {
    englishName: 'Basketball court',
    icon: 'https://storage.googleapis.com/waseet-dev/amenities/ph--court-basketball.png',
    isRequired: false,
    showInSummary: true,
    hiddenToBuyers: false,
    isAmenity: true,
    showInComparison: true,
    showInFilters: false,
  },
  {
    englishName: 'Jacuzzi',
    icon: 'https://storage.googleapis.com/waseet-dev/amenities/ph--bathtub.png',
    isRequired: false,
    showInSummary: true,
    hiddenToBuyers: false,
    isAmenity: true,
    showInComparison: true,
    showInFilters: false,
  },
  {
    englishName: 'BBQ area',
    icon: 'https://storage.googleapis.com/waseet-dev/amenities/ph--hamburger.png',
    isRequired: false,
    showInSummary: true,
    hiddenToBuyers: false,
    isAmenity: true,
    showInComparison: true,
    showInFilters: true,
  },

  {
    englishName: 'Maids room',
    icon: 'https://storage.googleapis.com/waseet-dev/amenities/ph--broom.png',
    isRequired: false,
    showInSummary: true,
    hiddenToBuyers: false,
    isAmenity: true,
    showInComparison: true,
    showInFilters: true,
  },
  {
    englishName: 'Pets allowed',
    icon: 'https://storage.googleapis.com/waseet-dev/amenities/ph--dog.png',
    isRequired: false,
    showInSummary: true,
    hiddenToBuyers: false,
    isAmenity: true,
    showInComparison: true,
    showInFilters: true,
  },
  {
    englishName: 'Balcony',
    icon: 'https://storage.googleapis.com/waseet-dev/amenities/ph--bird.png',
    isRequired: false,
    showInSummary: true,
    hiddenToBuyers: false,
    isAmenity: true,
    showInComparison: true,
    showInFilters: false,
  },
  {
    englishName: 'Gym',
    icon: 'https://storage.googleapis.com/waseet-dev/amenities/ph--barbell.png',
    isRequired: false,
    showInSummary: true,
    hiddenToBuyers: false,
    isAmenity: true,
    showInComparison: true,
    showInFilters: true,
  },
  {
    englishName: 'Playground',
    icon: 'https://storage.googleapis.com/waseet-dev/amenities/ph--court-basketball.png',
    isRequired: false,
    showInSummary: true,
    hiddenToBuyers: false,
    isAmenity: true,
    showInComparison: true,
    showInFilters: false,
  },
  {
    englishName: 'Parking',
    icon: 'https://storage.googleapis.com/waseet-dev/amenities/ph--car-profile.png',
    isRequired: false,
    showInSummary: true,
    hiddenToBuyers: false,
    isAmenity: true,
    showInComparison: true,
    showInFilters: true,
  },
  {
    englishName: 'Security',
    icon: 'https://storage.googleapis.com/waseet-dev/amenities/ph--security-camera.png',
    isRequired: false,
    showInSummary: true,
    hiddenToBuyers: false,
    isAmenity: true,
    showInComparison: true,
    showInFilters: true,
  },
  {
    englishName: 'Air conditioning',
    icon: 'https://storage.googleapis.com/waseet-dev/amenities/ph--falseflake.png',
    isRequired: false,
    showInSummary: true,
    hiddenToBuyers: false,
    isAmenity: true,
    showInComparison: true,
    showInFilters: true,
  },
  {
    englishName: 'Storage room',
    icon: 'https://storage.googleapis.com/waseet-dev/amenities/ph--warehouse.png',
    isRequired: false,
    showInSummary: true,
    hiddenToBuyers: false,
    isAmenity: true,
    showInComparison: true,
    showInFilters: false,
  },
  {
    englishName: 'Laundry room',
    icon: 'https://storage.googleapis.com/waseet-dev/amenities/ph--washing-machine.png',
    isRequired: false,
    showInSummary: true,
    hiddenToBuyers: false,
    isAmenity: true,
    showInComparison: true,
    showInFilters: false,
  },
  {
    englishName: 'Conference room',
    icon: 'https://storage.googleapis.com/waseet-dev/amenities/ph--microphone-stage.png',
    isRequired: false,
    showInSummary: true,
    hiddenToBuyers: false,
    isAmenity: true,
    showInComparison: true,
    showInFilters: false,
  },
  {
    englishName: 'Gated community',
    icon: 'https://storage.googleapis.com/waseet-dev/amenities/ph--wall.png',
    isRequired: false,
    showInSummary: true,
    hiddenToBuyers: false,
    isAmenity: true,
    showInComparison: true,
    showInFilters: true,
  },
  {
    englishName: 'Indoor play area',
    icon: 'https://storage.googleapis.com/waseet-dev/amenities/ph--bowling-ball.png',
    isRequired: false,
    showInSummary: true,
    hiddenToBuyers: false,
    isAmenity: true,
    showInComparison: true,
    showInFilters: false,
  },
  {
    englishName: 'Covered parking',
    icon: 'https://storage.googleapis.com/waseet-dev/amenities/ph--car-simple.png',
    isRequired: false,
    showInSummary: true,
    hiddenToBuyers: false,
    isAmenity: true,
    showInComparison: true,
    showInFilters: false,
  },
  {
    englishName: 'Wifi',
    icon: 'https://storage.googleapis.com/waseet-dev/amenities/ph--wifi-medium.png',
    isRequired: false,
    showInSummary: true,
    hiddenToBuyers: false,
    isAmenity: true,
    showInComparison: true,
    showInFilters: true,
  },
  {
    englishName: 'Elevator',
    icon: 'https://storage.googleapis.com/waseet-dev/amenities/ph--elevator-duotone.png',
    isRequired: false,
    showInSummary: true,
    hiddenToBuyers: false,
    isAmenity: true,
    showInComparison: true,
    showInFilters: true,
  },
];
