/*
 * Copyright (c) 2024, Waseet LLC. All rights reserved.
 * For license. See license.txt
 */

import { CityEntitity } from '../../entities/city.entity';

export const CityFactory: Partial<CityEntitity>[] = [
  {
    city: 'Cairo',
    lat: '30.0444',
    lng: '31.2358',
    country: 'Egypt',
    iso2: 'EG',
    arabic_name: '',
    admin_name: 'Al Qāhirah',
  },
  {
    city: 'Giza',
    lat: '29.9870',
    lng: '31.2118',
    country: 'Egypt',
    iso2: 'EG',
    arabic_name: '',
    admin_name: 'Al Jīzah',
  },
  {
    city: 'Alexandria',
    lat: '31.1975',
    lng: '29.8925',
    country: 'Egypt',
    iso2: 'EG',
    arabic_name: '',
    admin_name: 'Al Iskandarīyah',
  },
  {
    city: 'Shubrā al Khaymah',
    lat: '30.1286',
    lng: '31.2422',
    country: 'Egypt',
    iso2: 'EG',
    arabic_name: '',
    admin_name: 'Al Qalyūbīyah',
  },
  {
    city: 'Sinnūris',
    lat: '29.4072',
    lng: '30.8667',
    country: 'Egypt',
    iso2: 'EG',
    arabic_name: '',
    admin_name: 'Al Fayyūm',
  },
  {
    city: 'Al Manşūrah',
    lat: '31.0500',
    lng: '31.3833',
    country: 'Egypt',
    iso2: 'EG',
    arabic_name: '',
    admin_name: 'Ad Daqahlīyah',
  },
  {
    city: 'Ḩalwān',
    lat: '29.8453',
    lng: '31.3333',
    country: 'Egypt',
    iso2: 'EG',
    arabic_name: '',
    admin_name: 'Al Qāhirah',
  },
  {
    city: 'Al Maḩallah al Kubrá',
    lat: '30.9686',
    lng: '31.1636',
    country: 'Egypt',
    iso2: 'EG',
    arabic_name: '',
    admin_name: 'Al Gharbīyah',
  },
  {
    city: 'Shibīn al Qanāţir',
    lat: '30.3133',
    lng: '31.3214',
    country: 'Egypt',
    iso2: 'EG',
    arabic_name: '',
    admin_name: 'Al Qalyūbīyah',
  },
  {
    city: 'Al Fayyūm',
    lat: '29.3084',
    lng: '30.8441',
    country: 'Egypt',
    iso2: 'EG',
    arabic_name: '',
    admin_name: 'Al Fayyūm',
  },
  {
    city: 'Akhmīm',
    lat: '26.5667',
    lng: '31.7500',
    country: 'Egypt',
    iso2: 'EG',
    arabic_name: '',
    admin_name: 'Sūhāj',
  },
  {
    city: 'Al Marāghah',
    lat: '26.7000',
    lng: '31.6000',
    country: 'Egypt',
    iso2: 'EG',
    arabic_name: '',
    admin_name: 'Sūhāj',
  },
  {
    city: 'Ţanţā',
    lat: '30.7833',
    lng: '31.0000',
    country: 'Egypt',
    iso2: 'EG',
    arabic_name: '',
    admin_name: 'Al Gharbīyah',
  },
  {
    city: 'Awsīm',
    lat: '30.1167',
    lng: '31.1333',
    country: 'Egypt',
    iso2: 'EG',
    arabic_name: '',
    admin_name: 'Al Jīzah',
  },
  {
    city: 'Asyūţ',
    lat: '27.1833',
    lng: '31.1667',
    country: 'Egypt',
    iso2: 'EG',
    arabic_name: '',
    admin_name: 'Asyūţ',
  },
  {
    city: 'Az Zaqāzīq',
    lat: '30.5667',
    lng: '31.5000',
    country: 'Egypt',
    iso2: 'EG',
    arabic_name: '',
    admin_name: 'Ash Sharqīyah',
  },
  {
    city: 'Al ‘Ajamī',
    lat: '31.0959',
    lng: '29.7604',
    country: 'Egypt',
    iso2: 'EG',
    arabic_name: '',
    admin_name: 'Al Iskandarīyah',
  },

  {
    city: 'Shibīn al Kawm',
    lat: '30.5586',
    lng: '31.0100',
    country: 'Egypt',
    iso2: 'EG',
    arabic_name: '',
    admin_name: 'Al Minūfīyah',
  },
  {
    city: 'Râs el-Barr',
    lat: '31.5125',
    lng: '31.8256',
    country: 'Egypt',
    iso2: 'EG',
    arabic_name: '',
    admin_name: 'Ad Daqahlīyah',
  },
  {
    city: 'Al ‘Āshir min Ramaḑān',
    lat: '30.3065',
    lng: '31.7415',
    country: 'Egypt',
    iso2: 'EG',
    arabic_name: '',
    admin_name: 'Ash Sharqīyah',
  },
  {
    city: 'Damanhūr',
    lat: '31.0361',
    lng: '30.4694',
    country: 'Egypt',
    iso2: 'EG',
    arabic_name: '',
    admin_name: 'Al Buḩayrah',
  },
  {
    city: 'Al Minyā',
    lat: '28.1194',
    lng: '30.7444',
    country: 'Egypt',
    iso2: 'EG',
    arabic_name: '',
    admin_name: 'Al Minyā',
  },
  {
    city: 'Mallawī',
    lat: '27.7333',
    lng: '30.8333',
    country: 'Egypt',
    iso2: 'EG',
    arabic_name: '',
    admin_name: 'Al Minyā',
  },
  {
    city: 'Damietta',
    lat: '31.4167',
    lng: '31.8214',
    country: 'Egypt',
    iso2: 'EG',
    arabic_name: '',
    admin_name: 'Dumyāţ',
  },
  {
    city: 'Qinā',
    lat: '26.1667',
    lng: '32.7167',
    country: 'Egypt',
    iso2: 'EG',
    arabic_name: '',
    admin_name: 'Qinā',
  },
  {
    city: 'Banī Suwayf',
    lat: '29.0667',
    lng: '31.0833',
    country: 'Egypt',
    iso2: 'EG',
    arabic_name: '',
    admin_name: 'Banī Suwayf',
  },
  {
    city: 'Banhā',
    lat: '30.4667',
    lng: '31.1833',
    country: 'Egypt',
    iso2: 'EG',
    arabic_name: '',
    admin_name: 'Al Qalyūbīyah',
  },
  {
    city: 'Qalyūb',
    lat: '30.1997',
    lng: '31.2053',
    country: 'Egypt',
    iso2: 'EG',
    arabic_name: '',
    admin_name: 'Al Qalyūbīyah',
  },
  {
    city: 'Kafr ash Shaykh',
    lat: '31.1117',
    lng: '30.9458',
    country: 'Egypt',
    iso2: 'EG',
    arabic_name: '',
    admin_name: 'Kafr ash Shaykh',
  },
  {
    city: 'Disūq',
    lat: '31.1422',
    lng: '30.6450',
    country: 'Egypt',
    iso2: 'EG',
    arabic_name: '',
    admin_name: 'Kafr ash Shaykh',
  },
  {
    city: 'Mīt Ghamr',
    lat: '30.7167',
    lng: '31.2500',
    country: 'Egypt',
    iso2: 'EG',
    arabic_name: '',
    admin_name: 'Ad Daqahlīyah',
  },
  {
    city: 'Munūf',
    lat: '30.4658',
    lng: '30.9308',
    country: 'Egypt',
    iso2: 'EG',
    arabic_name: '',
    admin_name: 'Al Minūfīyah',
  },
  {
    city: 'Fāqūs',
    lat: '30.7282',
    lng: '31.7970',
    country: 'Egypt',
    iso2: 'EG',
    arabic_name: '',
    admin_name: 'Ash Sharqīyah',
  },
  {
    city: 'Jirjā',
    lat: '26.3333',
    lng: '31.9000',
    country: 'Egypt',
    iso2: 'EG',
    arabic_name: '',
    admin_name: 'Sūhāj',
  },
  {
    city: 'Al Badrashayn',
    lat: '29.8520',
    lng: '31.2760',
    country: 'Egypt',
    iso2: 'EG',
    arabic_name: '',
    admin_name: 'Al Jīzah',
  },
  {
    city: 'Ibshawāy',
    lat: '29.4447',
    lng: '30.7107',
    country: 'Egypt',
    iso2: 'EG',
    arabic_name: '',
    admin_name: 'Al Fayyūm',
  },
  {
    city: 'Al Khānkah',
    lat: '30.1601',
    lng: '31.3133',
    country: 'Egypt',
    iso2: 'EG',
    arabic_name: '',
    admin_name: 'Al Qalyūbīyah',
  },
  {
    city: '‘Izbat al Burj',
    lat: '31.5031',
    lng: '31.8411',
    country: 'Egypt',
    iso2: 'EG',
    arabic_name: '',
    admin_name: 'Ad Daqahlīyah',
  },
  {
    city: 'Kirdāsah',
    lat: '30.0320',
    lng: '31.1104',
    country: 'Egypt',
    iso2: 'EG',
    arabic_name: '',
    admin_name: 'Al Jīzah',
  },
  {
    city: 'Abnūb',
    lat: '27.2667',
    lng: '31.1500',
    country: 'Egypt',
    iso2: 'EG',
    arabic_name: '',
    admin_name: 'Asyūţ',
  },
  {
    city: 'Al Minshāh',
    lat: '26.4833',
    lng: '31.8000',
    country: 'Egypt',
    iso2: 'EG',
    arabic_name: '',
    admin_name: 'Sūhāj',
  },
  {
    city: 'Al Qurayn',
    lat: '30.6161',
    lng: '31.7353',
    country: 'Egypt',
    iso2: 'EG',
    arabic_name: '',
    admin_name: 'Ash Sharqīyah',
  },
  {
    city: 'Abū Za‘bal',
    lat: '30.2415',
    lng: '31.4110',
    country: 'Egypt',
    iso2: 'EG',
    arabic_name: '',
    admin_name: 'Al Qalyūbīyah',
  },
  {
    city: 'Al Balyanā',
    lat: '26.2333',
    lng: '32.0000',
    country: 'Egypt',
    iso2: 'EG',
    arabic_name: '',
    admin_name: 'Sūhāj',
  },
  {
    city: 'Al ‘Ayyāţ',
    lat: '29.6167',
    lng: '31.2500',
    country: 'Egypt',
    iso2: 'EG',
    arabic_name: '',
    admin_name: 'Al Jīzah',
  },
  {
    city: 'Al Badārī',
    lat: '26.9925',
    lng: '31.4156',
    country: 'Egypt',
    iso2: 'EG',
    arabic_name: '',
    admin_name: 'Asyūţ',
  },
  {
    city: 'Kafr al Kurdī',
    lat: '31.1429',
    lng: '31.7826',
    country: 'Egypt',
    iso2: 'EG',
    arabic_name: '',
    admin_name: 'Ad Daqahlīyah',
  },
  {
    city: 'Abū Qīr',
    lat: '31.3167',
    lng: '30.0667',
    country: 'Egypt',
    iso2: 'EG',
    arabic_name: '',
    admin_name: 'Al Iskandarīyah',
  },
  {
    city: 'Qahā',
    lat: '30.2833',
    lng: '31.2000',
    country: 'Egypt',
    iso2: 'EG',
    arabic_name: '',
    admin_name: 'Al Qalyūbīyah',
  },
  {
    city: 'Al Karnak',
    lat: '25.7186',
    lng: '32.6586',
    country: 'Egypt',
    iso2: 'EG',
    arabic_name: '',
    admin_name: 'Al Uqşur',
  },
  {
    city: 'Kafr Shukr',
    lat: '30.5470',
    lng: '31.2673',
    country: 'Egypt',
    iso2: 'EG',
    arabic_name: '',
    admin_name: 'Al Minūfīyah',
  },
  {
    city: 'Mīt Namā',
    lat: '30.1453',
    lng: '31.2343',
    country: 'Egypt',
    iso2: 'EG',
    arabic_name: '',
    admin_name: 'Al Qalyūbīyah',
  },
  {
    city: 'Banī Murr',
    lat: '27.2272',
    lng: '31.1944',
    country: 'Egypt',
    iso2: 'EG',
    arabic_name: '',
    admin_name: 'Asyūţ',
  },
  {
    city: 'Al Madāmūd',
    lat: '25.7167',
    lng: '32.6500',
    country: 'Egypt',
    iso2: 'EG',
    arabic_name: '',
    admin_name: 'Al Uqşur',
  },
  {
    city: 'Birqāsh',
    lat: '30.1692',
    lng: '31.0417',
    country: 'Egypt',
    iso2: 'EG',
    arabic_name: '',
    admin_name: 'Al Jīzah',
  },
  {
    city: 'Kafr Ţaḩlah',
    lat: '30.3981',
    lng: '31.1333',
    country: 'Egypt',
    iso2: 'EG',
    arabic_name: '',
    admin_name: 'Al Qalyūbīyah',
  },
];
