/*
 * Copyright (c) 2024, Waseet LLC. All rights reserved.
 * For license. See license.txt
 */

export const IssueFactory = [
  {
    category: 'Support',
    parentReason: 'Account Issues',
    parentArabicName: null,
    childReason: 'Cannot Reset Password',
    childArabicName: null,
  },
  {
    category: 'Support',
    parentReason: 'Account Issues',
    parentArabicName: null,
    childReason: 'Email not being sent',
    childArabicName: null,
  },
  {
    category: 'Support',
    parentReason: 'Payment Issues',
    parentArabicName: null,
    childReason: 'Failed Transaction',
    childArabicName: null,
  },
  {
    category: 'Support',
    parentReason: 'Payment Issues',
    parentArabicName: null,
    childReason: 'Refund Request',
    childArabicName: null,
  },
  {
    category: 'Support',
    parentReason: 'Payment Issues',
    parentArabicName: null,
    childReason: 'Incorrect Billing',
    childArabicName: null,
  },
  {
    category: 'Support',
    parentReason: 'Payment Issues',
    parentArabicName: null,
    childReason: 'Duplicate Charges',
    childArabicName: null,
  },
  {
    category: 'Support',
    parentReason: 'Technical Issues',
    parentArabicName: null,
    childReason: 'App Crashes',
    childArabicName: null,
  },
  {
    category: 'Support',
    parentReason: 'Technical Issues',
    parentArabicName: null,
    childReason: 'Feature Not Working',
    childArabicName: null,
  },
  {
    category: 'Support',
    parentReason: 'Technical Issues',
    parentArabicName: null,
    childReason: 'Error Messages',
    childArabicName: null,
  },
  {
    category: 'Support',
    parentReason: 'Service Requests',
    parentArabicName: null,
    childReason: 'New Feature Request',
    childArabicName: null,
  },
  {
    category: 'Support',
    parentReason: 'Feedback',
    parentArabicName: null,
    childReason: 'General Feedback',
    childArabicName: null,
  },
  {
    category: 'Support',
    parentReason: 'Feedback',
    parentArabicName: null,
    childReason: 'Feature Suggestions',
    childArabicName: null,
  },
  {
    category: 'Support',
    parentReason: 'Feedback',
    parentArabicName: null,
    childReason: 'Complaints',
    childArabicName: null,
  },
  {
    category: 'Support',
    parentReason: 'Other',
    parentArabicName: null,
    childReason: 'Other',
    childArabicName: null,
  },
  {
    category: 'Flagging Listings',
    parentReason: 'Listing Accuracy',
    parentArabicName: null,
    childReason: 'Incorrect Information',
    childArabicName: null,
  },
  {
    category: 'Flagging Listings',
    parentReason: 'Listing Accuracy',
    parentArabicName: null,
    childReason: 'Misleading Photos',
    childArabicName: null,
  },
  {
    category: 'Flagging Listings',
    parentReason: 'Listing Accuracy',
    parentArabicName: null,
    childReason: 'Wrong Location',
    childArabicName: null,
  },
  {
    category: 'Flagging Listings',
    parentReason: 'Listing Accuracy',
    parentArabicName: null,
    childReason: 'Incorrect Pricing',
    childArabicName: null,
  },
  {
    category: 'Flagging Listings',
    parentReason: 'Inappropriate Content',
    parentArabicName: null,
    childReason: 'Offensive Language',
    childArabicName: null,
  },
  {
    category: 'Flagging Listings',
    parentReason: 'Inappropriate Content',
    parentArabicName: null,
    childReason: 'Discriminatory Content',
    childArabicName: null,
  },
  {
    category: 'Flagging Listings',
    parentReason: 'Inappropriate Content',
    parentArabicName: null,
    childReason: 'Spam or Scam',
    childArabicName: null,
  },
  {
    category: 'Flagging Listings',
    parentReason: 'Policy Violations',
    parentArabicName: null,
    childReason: 'Duplicate Listing',
    childArabicName: null,
  },
  {
    category: 'Flagging Listings',
    parentReason: 'Policy Violations',
    parentArabicName: null,
    childReason: 'Privacy Violations',
    childArabicName: null,
  },
  {
    category: 'Flagging Listings',
    parentReason: 'Other',
    parentArabicName: null,
    childReason: 'Other Issues',
    childArabicName: null,
  },
  {
    category: 'Flagging Listings',
    parentReason: 'Other',
    parentArabicName: null,
    childReason: 'User Report',
    childArabicName: null,
  },
];
