/*
 * Copyright (c) 2024, Waseet LLC. All rights reserved.
 * For license. See license.txt
 */

import { DeepPartial } from 'typeorm';
import { NotificationMessages } from '../../entities/notification-message.entity';

export const NotificationMessageFactory: DeepPartial<NotificationMessages>[] = [
  {
    scope: 'Offers',
    event: 'Create',
    email: true,
    pushNotification: true,
    systemNotification: true,
    recipients: 'Offer Creator',
    title: 'Offer Created',
    body: `Hi {{username}}, you have successfully created an offer on a listing.`,
    arabicTitle: 'تم إنشاء العرض',
    arabicBody: `مرحبًا {{arabicUsername}}، لقد قمت بإنشاء عرض بنجاح على قائمة.`,
  },
  {
    scope: 'Offers',
    event: 'Create',
    email: true,
    pushNotification: true,
    systemNotification: true,
    recipients: 'Seller',
    title: 'Offer Created',
    body: `Hi {{username}}, an offer has been made on your listing!`,
    arabicTitle: 'تم إنشاء العرض',
    arabicBody: `مرحبًا ،{{arabicUsername}} تم تقديم عرض على قائمتك!`,
  },
  {
    scope: 'Offers',
    event: 'Update',
    email: true,
    pushNotification: true,
    systemNotification: true,
    recipients: 'Offer Creator',
    title: 'Offer Edited',
    body: `Hi {{username}}, you have successfully edited your offer on a listing.`,
    arabicTitle: 'تعديل العرض',
    arabicBody: `مرحبًا {{arabicUsername}}، لقد قمت بتعديل عرضك بنجاح على قائمة.`,
  },
  {
    scope: 'Offers',
    event: 'Update',
    email: true,
    pushNotification: true,
    systemNotification: true,
    recipients: 'Seller',
    title: 'Offer Edited',
    body: `Hi {{username}}, an offer on your listing has just been updated.`,
    arabicTitle: 'تعديل العرض',
    arabicBody: 'مرحبًا [الاسم الأول]، لقد تم تحديث عرض على قائمتك.',
  },
  {
    scope: 'Offers',
    event: 'Response',
    email: true,
    pushNotification: true,
    systemNotification: true,
    recipients: 'Offer Creator',
    title: 'Offer Response',
    body: `Hi {{username}}, the seller has declined/approved your offer.`,
    arabicTitle: 'رد العرض',
    arabicBody: 'مرحبًا [الاسم الأول]، لقد رفض/وافق البائع على عرضك.',
  },
  {
    scope: 'Offers',
    event: 'Response',
    email: true,
    pushNotification: true,
    systemNotification: true,
    recipients: 'Seller',
    title: 'Offer Response',
    body: `Hi {{username}}, you have just approved/declined an offer on your listing.`,
    arabicTitle: 'رد العرض',
    arabicBody: 'مرحبًا [الاسم الأول]، لقد وافقت/رفضت للتو عرضًا على قائمتك.',
  },
  {
    scope: 'Live Auction',
    event: 'Bids',
    email: true,
    pushNotification: true,
    systemNotification: true,
    recipients: 'Listing Bidder and Seller',
    title: 'New Bid',
    body: `Hi {{username}}, a new bid has been placed on a listing you're watching!`,
    arabicTitle: 'عرض جديد',
    arabicBody: 'مرحبًا [الاسم الأول]، تم وضع عرض جديد على قائمة تتابعها!',
  },
  {
    scope: 'Live Auction',
    event: 'Results',
    email: true,
    pushNotification: true,
    systemNotification: true,
    recipients: 'Bidder',
    title: 'You have lost',
    body: `Hi {{username}}, unfortunately, your bid was not the highest. We appreciate your participation.`,
    arabicTitle: 'لقد خسرت',
    arabicBody: 'مرحبًا [الاسم الأول]، للأسف لم يكن عرضك الأعلى. نقدر مشاركتك.',
  },
  {
    scope: 'Live Auction',
    event: 'Results',
    email: true,
    pushNotification: true,
    systemNotification: true,
    recipients: 'Bidder',
    title: 'You have won',
    body: `Hi {{username}}, congratulations! You are the successful bidder. We're thrilled to inform you that you've won [item title].`,
    arabicTitle: 'لقد ربحت',
    arabicBody:
      'مرحبًا [الاسم الأول]، تهانينا! أنت الفائز بالعرض. يسرنا إبلاغك أنك فزت ب[عنوان العنصر].',
  },
  {
    scope: 'Live Auction',
    event: 'Results',
    email: true,
    pushNotification: true,
    systemNotification: true,
    recipients: 'Seller',
    title: 'Listing Purchased',
    body: `Hi {{username}}, good news! Your item has been successfully sold at the auction.`,
    arabicTitle: 'تم شراء القائمة',
    arabicBody:
      'مرحبًا [الاسم الأول]، أخبار جيدة! تم بيع عنصرك بنجاح في المزاد.',
  },
  {
    scope: 'Live Auction',
    event: 'Results',
    email: true,
    pushNotification: true,
    systemNotification: true,
    recipients: 'Seller',
    title: 'No Bids',
    body: `Hi {{username}}, we're sorry to inform you that your listing did not receive any bids this time.`,
    arabicTitle: 'لا يوجد عروض',
    arabicBody:
      'مرحبًا [الاسم الأول]، نأسف لإبلاغك أن قائمتك لم تتلق أي عروض هذه المرة.',
  },
  {
    scope: 'Live Auction',
    event: 'Last minute',
    email: true,
    pushNotification: true,
    systemNotification: true,
    recipients: 'Listing Bidder and Seller',
    title: 'Last Minute!',
    body: `Hi {{username}}, the auction is about to close. We are down to the final minute—don't miss out!`,
    arabicTitle: 'اللحظات الأخيرة!',
    arabicBody:
      'مرحبًا [الاسم الأول]، المزاد على وشك الإغلاق. لقد وصلنا إلى الدقيقة الأخيرة—لا تفوت الفرصة!',
  },
  {
    scope: 'Live Auction',
    event: '15 minutes to end',
    email: true,
    pushNotification: true,
    systemNotification: true,
    recipients: 'Listing Bidder and Seller',
    title: '15 minutes left!',
    body: `Hi {{username}}, just a reminder that only 15 minutes are left in the auction. Don't miss your chance to win!`,
    arabicTitle: '١٥ دقيقة متبقية!',
    arabicBody:
      'مرحبًا [الاسم الأول]، فقط تذكير أنه تبقى فقط ١٥ دقيقة في المزاد. لا تفوت فرصتك للفوز!',
  },
  {
    scope: 'Listings in Saved searches',
    event: 'Created',
    email: true,
    pushNotification: true,
    systemNotification: true,
    recipients: 'User that has searched',
    title: 'Listing Created!',
    body: `Hi {{username}}, great news! A new listing that matches your saved search criteria has just been posted. Check it out now!`,
    arabicTitle: 'قائمة جديدة!',
    arabicBody:
      'مرحبًا [الاسم الأول]، أخبار رائعة! تم نشر قائمة جديدة تطابق معايير البحث المحفوظة لديك. تفقدها الآن!',
  },
  {
    scope: 'Listings in Wishlist',
    event: 'Price change',
    email: true,
    pushNotification: true,
    systemNotification: true,
    recipients: 'User that has listing in wishlist',
    title: 'Price Changed!',
    body: `Hi {{username}}, heads up! The price of an item in your wishlist has been updated. Check out the new price now.`,
    arabicTitle: 'تغيير في السعر!',
    arabicBody:
      'مرحبًا [الاسم الأول]، انتبه! تم تحديث سعر عنصر في قائمة أمنياتك. تفقد السعر الجديد الآن.',
  },
  {
    scope: 'Upcoming Auctions',
    event: 'A month before',
    email: true,
    pushNotification: true,
    systemNotification: true,
    recipients: 'All platform',
    title: 'Auction Alert',
    body: `Hi {{username}}, mark your calendars! Our next exciting auction event is just a month away. Visit our platform to preview the items.`,
    arabicTitle: 'تنبيه المزاد',
    arabicBody:
      'مرحبًا [الاسم الأول]، ضع علامة على تقويمك! المزاد القادم المثير على بُعد شهر فقط. زر منصتنا لمعاينة العناصر.',
  },
  {
    scope: 'Upcoming Auctions',
    event: 'Weekly',
    email: true,
    pushNotification: true,
    systemNotification: true,
    recipients: 'All platform',
    title: 'Auction Alert',
    body: `Hi {{username}}, just {{count}} weeks to go until our upcoming auction! Make sure to check out the listings or enlist your own properties.`,
    arabicTitle: 'تنبيه المزاد',
    arabicBody:
      'مرحبًا [الاسم الأول]، فقط {{count}} أسابيع حتى مزادنا القادم! تأكد من مراجعة القوائم أو إدراج عقاراتك.',
  },
  {
    scope: 'Upcoming Auctions',
    event: 'Daily',
    email: true,
    pushNotification: true,
    systemNotification: true,
    recipients: 'Users enlisted to bid and sellers',
    title: 'Auction Alert',
    body: `Hi {{username}}, countdown to the auction: Only {{count}} days to go! Get ready for some fantastic bidding opportunities.`,
    arabicTitle: 'تنبيه المزاد',
    arabicBody:
      'مرحبًا [الاسم الأول]، العد التنازلي للمزاد: فقط {{count}} أيام متبقية! استعد لفرص المزايدة الرائعة.',
  },
  {
    scope: 'Upcoming Auctions',
    event: '12- Hour before',
    email: true,
    pushNotification: true,
    systemNotification: true,
    recipients: 'Users enlisted to bid and sellers',
    title: 'Auction Alert',
    body: `Hi {{username}}, the countdown is on! Only 12 hours to go until our auction. Make sure you're prepared to bid!`,
    arabicTitle: 'تنبيه المزاد',
    arabicBody:
      'مرحبًا {{username}}، العد التنازلي قائم! فقط 12 ساعة حتى موعد المزاد. تأكد من استعدادك للمزايدة!',
  },
  {
    scope: 'Invoices',
    event: 'Create',
    email: true,
    pushNotification: true,
    systemNotification: true,
    recipients: 'Payer',
    title: 'Successful Payment',
    body: `Hi {{username}}, your payment has been successfully processed. Thank you for your transaction!"`,
    arabicTitle: 'دفع ناجح',
    arabicBody:
      'مرحبًا [الاسم الأول]، تم معالجة دفعتك بنجاح. شكرًا لك على معاملتك!',
  },
  {
    scope: 'Registration',
    event: 'email Verifiation',
    email: true,
    pushNotification: true,
    systemNotification: true,
    recipients: 'Registering user',
    title: 'Verify Your email',
    body: 'Please verify your email address to complete your registration and start using your account.',
    arabicTitle: 'تأكيد بريدك الإلكتروني',
    arabicBody: 'يرجى تأكيد بريدك الإلكتروني لإكمال تسجيلك وبدء استخدام حسابك.',
  },
  {
    scope: 'Listing',
    event: 'Create',
    email: true,
    pushNotification: true,
    systemNotification: true,
    recipients: 'Seller "listing an item"',
    title: 'Complete Your Listing',
    body: "It looks like you didn't finish creating your listing. Please complete it to make it live.",
    arabicTitle: 'إكمال إنشاء قائمتك',
    arabicBody: 'يبدو أنك لم تنتهي من عرض عقارك. يرجى إكمالها لنشرها.',
  },
  {
    scope: 'Offers',
    event: 'Accepted',
    email: true,
    pushNotification: true,
    systemNotification: true,
    recipients: 'Buyer',
    title: 'Finalize Your Purchase',
    body: 'The seller has accepted your offer! Please complete the buying process to secure your new property.',
    arabicTitle: 'إتمام عملية الشراء',
    arabicBody:
      'لقد وافق البائع على عرضك! يرجى إتمام عملية الشراء لتأمين عقارك الجديد.',
  },
  {
    scope: 'Auction',
    event: 'If Win',
    email: true,
    pushNotification: true,
    systemNotification: true,
    recipients: 'Buyer',
    title: 'Complete Auction Purchase',
    body: 'Congratulations on winning the auction! Please complete the purchase to finalize the transaction.',
    arabicTitle: 'إتمام شراء المزاد',
    arabicBody:
      'تهانينا على الفوز بالمزاد! يرجى إكمال عملية الشراء لإنهاء الصفقة.',
  },
  {
    scope: 'Auction',
    event: 'If Sold',
    email: true,
    pushNotification: true,
    systemNotification: true,
    recipients: 'Seller',
    title: 'Confirm Auction Contract',
    body: 'The auction has ended and your item was sold. Please agree to the contract to finalize the sale.',
    arabicTitle: 'تأكيد عقد المزاد',
    arabicBody:
      'انتهى المزاد وتم بيع عنصرك. يرجى الموافقة على العقد لإنهاء البيع.',
  },
  {
    scope: 'Offers',
    event: 'If Accepted Offer',
    email: true,
    pushNotification: true,
    systemNotification: true,
    recipients: 'Seller',
    title: 'Confirm Sale Contract',
    body: 'You have accepted an offer on your listing. Please confirm the sale contract to proceed.',
    arabicTitle: 'تأكيد عقد البيع',
    arabicBody: 'لقد قبلت عرضًا على قائمتك. يرجى تأكيد عقد البيع للمتابعة.',
  },
  {
    scope: 'Service Provider Application',
    event: 'If Accepted',
    email: true,
    pushNotification: true,
    systemNotification: true,
    recipients: 'Service Provider',
    title: 'Sign Your Service Contract',
    body: 'Your application as a service provider has been accepted. Please sign the contract to begin.',
    arabicTitle: 'توقيع عقد مقدم الخدمة',
    arabicBody: 'تم قبول طلبك كمقدم خدمة. يرجى توقيع العقد للبدء.',
  },
  {
    scope: 'Service',
    event: 'Delivered',
    email: true,
    pushNotification: true,
    systemNotification: true,
    recipients: 'Listing Owner',
    title: 'Confirm Service Completion',
    body: 'Your service provider has reported their job as completed. Please confirm if the service is done.',
    arabicTitle: 'تأكيد إتمام الخدمة',
    arabicBody: 'أبلغ مقدم الخدمة عن إكمال عمله. يرجى تأكيد إتمام الخدمة.',
  },

  {
    scope: 'Workflow events',
    event: 'Workflow event trigger',
    email: true,
    pushNotification: true,
    systemNotification: true,
    recipients: 'Admin Approver',
    title: 'Request for Approval',
    body: 'Dear Admin we need your approval on admin action',
    arabicTitle: 'الرجاء الموافقة',
    arabicBody: 'الرجاء الموافقة علي تنفيذ هذا التغيير',
  },
  {
    scope: 'Request Created',
    event: 'Seller and buyer sent request info',
    email: true,
    pushNotification: true,
    systemNotification: true,
    recipients: 'Admin Deal Finalizer',
    title: 'Sale Pending',
    body: 'Dear Admin there is a sale pending on Waseet',
    arabicTitle: 'بيع معلق',
    arabicBody: 'الرجاء تنفيذ لبيع',
  },
  {
    scope: 'Request Created',
    event: 'Rental request sent from both parties',
    email: true,
    pushNotification: true,
    systemNotification: true,
    recipients: 'Admin Deal Finalizer',
    title: 'Rental Pending',
    body: 'Dear admin there is a rental pending on waseet',
    arabicTitle: 'ايجار معلق',
    arabicBody: 'الرجاء تنفيذ عقد الايجار',
  },
  {
    scope: 'Requests Management',
    event: 'Admin Change status',
    email: true,
    pushNotification: true,
    systemNotification: true,
    recipients: 'Both Parties',
    title: 'Request Status Change',
    body: 'Dear Owner/(Buyer/Rentee) your request status has been changed to (new Status)',
    arabicTitle: 'تغيير وضع الطلب',
    arabicBody: 'تم تغيير وضع الطلب ليكون : (وضع الطلب الجديد)',
  },
  {
    scope: 'Listing',
    event: 'Create',
    email: true,
    pushNotification: true,
    systemNotification: true,
    recipients: 'Admin listing approver',
    title: 'New Listing',
    body: 'Please review this new listing',
    arabicTitle: 'اعلان جديد',
    arabicBody: 'الرجاء النظر في هذا الاعلان الجديد',
  },
  {
    scope: 'Listing',
    event: 'Approved',
    email: true,
    pushNotification: true,
    systemNotification: true,
    recipients: 'Owner',
    title: 'Listing Published',
    body: 'Congratulations, Your listing is now live.',
    arabicTitle: 'تم نشر اعلاتك',
    arabicBody: 'مبروك، لقد تم نشر اعلانك',
  },
  {
    scope: 'Listing',
    event: 'Denied',
    email: true,
    pushNotification: true,
    systemNotification: true,
    recipients: 'Owner',
    title: 'Listing Denied',
    body: 'You listing has been denied for :',
    arabicTitle: 'تم رفض اعلانك',
    arabicBody: 'عفوا، لم يتم الموافقة علي اعلانك لسبب:',
  },
];
