/*
 * Copyright (c) 2024, Waseet LLC. All rights reserved.
 * For license. See license.txt
 */

//To update permission, delete all permisions in the table First
export const permissionFactory = [
  {
    permissionGroup: 'Users',
    description: null,
    name: 'Create User',
    useFlag: true,
    approveFlag: false,
    individualAccess: false,
    companyAccess: false,
    staffAccess: true,
    remarks: null,
  },
  {
    permissionGroup: 'Users',
    description: null,
    name: 'Read User',
    useFlag: true,
    approveFlag: false,
    individualAccess: false,
    companyAccess: false,
    staffAccess: true,
    remarks: null,
  },
  {
    permissionGroup: 'Users',
    description: null,
    name: 'Update User',
    useFlag: true,
    approveFlag: false,
    individualAccess: false,
    companyAccess: false,
    staffAccess: true,
    remarks: null,
  },
  {
    permissionGroup: 'Users',
    description: null,
    name: 'Delete User',
    useFlag: true,
    approveFlag: false,
    individualAccess: false,
    companyAccess: false,
    staffAccess: true,
    remarks: null,
  },
  {
    permissionGroup: 'Users',
    description: null,
    name: 'Export User',
    useFlag: true,
    approveFlag: false,
    individualAccess: false,
    companyAccess: false,
    staffAccess: true,
    remarks: null,
  },
  {
    permissionGroup: 'Users',
    description: null,
    name: 'Audit User',
    useFlag: true,
    approveFlag: false,
    individualAccess: false,
    companyAccess: false,
    staffAccess: true,
    remarks: null,
  },
  {
    permissionGroup: 'Roles',
    description: null,
    name: 'Create role',
    useFlag: true,
    approveFlag: false,
    individualAccess: false,
    companyAccess: false,
    staffAccess: true,
    remarks: null,
  },
  {
    permissionGroup: 'Roles',
    description: null,
    name: 'Read role',
    useFlag: true,
    approveFlag: false,
    individualAccess: false,
    companyAccess: false,
    staffAccess: true,
    remarks: null,
  },
  {
    permissionGroup: 'Roles',
    description: null,
    name: 'Update role',
    useFlag: true,
    approveFlag: false,
    individualAccess: false,
    companyAccess: false,
    staffAccess: true,
    remarks: null,
  },
  {
    permissionGroup: 'Roles',
    description: null,
    name: 'Delete role',
    useFlag: true,
    approveFlag: false,
    individualAccess: false,
    companyAccess: false,
    staffAccess: true,
    remarks: null,
  },
  {
    permissionGroup: 'Roles',
    description: null,
    name: 'Export role',
    useFlag: true,
    approveFlag: false,
    individualAccess: false,
    companyAccess: false,
    staffAccess: true,
    remarks: null,
  },
  {
    permissionGroup: 'Roles',
    description: null,
    name: 'Audit role',
    useFlag: true,
    approveFlag: false,
    individualAccess: false,
    companyAccess: false,
    staffAccess: true,
    remarks: null,
  },
  {
    permissionGroup: 'Listing Type',
    description: null,
    name: 'Create Listing Type',
    useFlag: true,
    approveFlag: false,
    individualAccess: false,
    companyAccess: false,
    staffAccess: true,
    remarks: null,
  },
  {
    permissionGroup: 'Listing Type',
    description: null,
    name: 'Read Listing Type',
    useFlag: true,
    approveFlag: false,
    individualAccess: false,
    companyAccess: false,
    staffAccess: true,
    remarks: null,
  },
  {
    permissionGroup: 'Listing Type',
    description: null,
    name: 'Update Listing Type',
    useFlag: true,
    approveFlag: false,
    individualAccess: false,
    companyAccess: false,
    staffAccess: true,
    remarks: null,
  },
  {
    permissionGroup: 'Listing Type',
    description: null,
    name: 'Delete Listing Type',
    useFlag: true,
    approveFlag: false,
    individualAccess: false,
    companyAccess: false,
    staffAccess: true,
    remarks: null,
  },
  {
    permissionGroup: 'Listing Type',
    description: null,
    name: 'Export Listing Type',
    useFlag: true,
    approveFlag: false,
    individualAccess: false,
    companyAccess: false,
    staffAccess: true,
    remarks: null,
  },
  {
    permissionGroup: 'Listing Type',
    description: null,
    name: 'Audit Listing Type',
    useFlag: true,
    approveFlag: false,
    individualAccess: false,
    companyAccess: false,
    staffAccess: true,
    remarks: null,
  },
  {
    permissionGroup: 'Attribute Sets',
    description: null,
    name: 'Create Attribute Set',
    useFlag: true,
    approveFlag: false,
    individualAccess: false,
    companyAccess: false,
    staffAccess: true,
    remarks: null,
  },
  {
    permissionGroup: 'Attribute Sets',
    description: null,
    name: 'Read Attribute Sets',
    useFlag: true,
    approveFlag: false,
    individualAccess: false,
    companyAccess: false,
    staffAccess: true,
    remarks: null,
  },
  {
    permissionGroup: 'Attribute Sets',
    description: null,
    name: 'Update Attribute Sets',
    useFlag: true,
    approveFlag: false,
    individualAccess: false,
    companyAccess: false,
    staffAccess: true,
    remarks: null,
  },
  {
    permissionGroup: 'Attribute Sets',
    description: null,
    name: 'Delete Attribute Sets',
    useFlag: true,
    approveFlag: false,
    individualAccess: false,
    companyAccess: false,
    staffAccess: true,
    remarks: null,
  },
  {
    permissionGroup: 'Attribute Sets',
    description: null,
    name: 'Export Attribute Sets',
    useFlag: true,
    approveFlag: false,
    individualAccess: false,
    companyAccess: false,
    staffAccess: true,
    remarks: null,
  },
  {
    permissionGroup: 'Attribute Sets',
    description: null,
    name: 'Audit Attribute Sets',
    useFlag: true,
    approveFlag: false,
    individualAccess: false,
    companyAccess: false,
    staffAccess: true,
    remarks: null,
  },
  {
    permissionGroup: 'Dashboard',
    description: null,
    name: 'Create dashboard',
    useFlag: true,
    approveFlag: false,
    individualAccess: false,
    companyAccess: false,
    staffAccess: true,
    remarks: null,
  },
  {
    permissionGroup: 'Dashboard',
    description: null,
    name: 'Read dashboard',
    useFlag: true,
    approveFlag: false,
    individualAccess: false,
    companyAccess: false,
    staffAccess: true,
    remarks: null,
  },
  {
    permissionGroup: 'Dashboard',
    description: null,
    name: 'Update dashboard',
    useFlag: true,
    approveFlag: false,
    individualAccess: false,
    companyAccess: false,
    staffAccess: true,
    remarks: null,
  },
  {
    permissionGroup: 'Dashboard',
    description: null,
    name: 'Delete dashboard',
    useFlag: true,
    approveFlag: false,
    individualAccess: false,
    companyAccess: false,
    staffAccess: true,
    remarks: null,
  },
  {
    permissionGroup: 'Dashboard',
    description: null,
    name: 'Export dashboard',
    useFlag: true,
    approveFlag: false,
    individualAccess: false,
    companyAccess: false,
    staffAccess: true,
    remarks: null,
  },
  {
    permissionGroup: 'Dashboard',
    description: null,
    name: 'Audit dashboard',
    useFlag: true,
    approveFlag: false,
    individualAccess: false,
    companyAccess: false,
    staffAccess: true,
    remarks: null,
  },
  {
    permissionGroup: 'CMS',
    description: null,
    name: 'Create CMS',
    useFlag: true,
    approveFlag: false,
    individualAccess: false,
    companyAccess: false,
    staffAccess: true,
    remarks: null,
  },
  {
    permissionGroup: 'CMS',
    description: null,
    name: 'Read CMS',
    useFlag: true,
    approveFlag: false,
    individualAccess: false,
    companyAccess: false,
    staffAccess: true,
    remarks: null,
  },
  {
    permissionGroup: 'CMS',
    description: null,
    name: 'Update CMS',
    useFlag: true,
    approveFlag: false,
    individualAccess: false,
    companyAccess: false,
    staffAccess: true,
    remarks: null,
  },
  {
    permissionGroup: 'CMS',
    description: null,
    name: 'Delete CMS',
    useFlag: true,
    approveFlag: false,
    individualAccess: false,
    companyAccess: false,
    staffAccess: true,
    remarks: null,
  },
  {
    permissionGroup: 'CMS',
    description: null,
    name: 'Export CMS',
    useFlag: true,
    approveFlag: false,
    individualAccess: false,
    companyAccess: false,
    staffAccess: true,
    remarks: null,
  },
  {
    permissionGroup: 'CMS',
    description: null,
    name: 'Audit CMS',
    useFlag: true,
    approveFlag: false,
    individualAccess: false,
    companyAccess: false,
    staffAccess: true,
    remarks: null,
  },
  {
    permissionGroup: 'CMS Categories',
    description: null,
    name: 'Create CMS Categories',
    useFlag: true,
    approveFlag: false,
    individualAccess: false,
    companyAccess: false,
    staffAccess: true,
    remarks: null,
  },
  {
    permissionGroup: 'CMS Categories',
    description: null,
    name: 'Read CMS Categories',
    useFlag: true,
    approveFlag: false,
    individualAccess: false,
    companyAccess: false,
    staffAccess: true,
    remarks: null,
  },
  {
    permissionGroup: 'CMS Categories',
    description: null,
    name: 'Update CMS Categories',
    useFlag: true,
    approveFlag: false,
    individualAccess: false,
    companyAccess: false,
    staffAccess: true,
    remarks: null,
  },
  {
    permissionGroup: 'CMS Categories',
    description: null,
    name: 'Delete CMS Categories',
    useFlag: true,
    approveFlag: false,
    individualAccess: false,
    companyAccess: false,
    staffAccess: true,
    remarks: null,
  },
  {
    permissionGroup: 'CMS Categories',
    description: null,
    name: 'Export CMS Categories',
    useFlag: true,
    approveFlag: false,
    individualAccess: false,
    companyAccess: false,
    staffAccess: true,
    remarks: null,
  },
  {
    permissionGroup: 'CMS Categories',
    description: null,
    name: 'Audit CMS Categories',
    useFlag: true,
    approveFlag: false,
    individualAccess: false,
    companyAccess: false,
    staffAccess: true,
    remarks: null,
  },
  {
    permissionGroup: 'Listings',
    description: null,
    name: 'Create Listing',
    useFlag: true,
    approveFlag: false,
    individualAccess: false,
    companyAccess: false,
    staffAccess: true,
    remarks: null,
  },
  {
    permissionGroup: 'Listings',
    description: null,
    name: 'Read Listing',
    useFlag: true,
    approveFlag: false,
    individualAccess: false,
    companyAccess: false,
    staffAccess: true,
    remarks: null,
  },
  {
    permissionGroup: 'Listings',
    description: null,
    name: 'Update Listing',
    useFlag: true,
    approveFlag: false,
    individualAccess: false,
    companyAccess: false,
    staffAccess: true,
    remarks: null,
  },
  {
    permissionGroup: 'Listings',
    description: null,
    name: 'Delete Listing',
    useFlag: true,
    approveFlag: false,
    individualAccess: false,
    companyAccess: false,
    staffAccess: true,
    remarks: null,
  },
  {
    permissionGroup: 'Listings',
    description: null,
    name: 'Export Listing',
    useFlag: true,
    approveFlag: false,
    individualAccess: false,
    companyAccess: false,
    staffAccess: true,
    remarks: null,
  },
  {
    permissionGroup: 'Listings',
    description: null,
    name: 'Audit Listing',
    useFlag: true,
    approveFlag: false,
    individualAccess: false,
    companyAccess: false,
    staffAccess: true,
    remarks: null,
  },
  {
    permissionGroup: 'Services',
    description: null,
    name: 'Create Service',
    useFlag: true,
    approveFlag: false,
    individualAccess: false,
    companyAccess: false,
    staffAccess: true,
    remarks: null,
  },
  {
    permissionGroup: 'Services',
    description: null,
    name: 'Read Service',
    useFlag: true,
    approveFlag: false,
    individualAccess: false,
    companyAccess: false,
    staffAccess: true,
    remarks: null,
  },
  {
    permissionGroup: 'Services',
    description: null,
    name: 'Update Service',
    useFlag: true,
    approveFlag: false,
    individualAccess: false,
    companyAccess: false,
    staffAccess: true,
    remarks: null,
  },
  {
    permissionGroup: 'Services',
    description: null,
    name: 'Delete Service',
    useFlag: true,
    approveFlag: false,
    individualAccess: false,
    companyAccess: false,
    staffAccess: true,
    remarks: null,
  },
  {
    permissionGroup: 'Services',
    description: null,
    name: 'Export Service',
    useFlag: true,
    approveFlag: false,
    individualAccess: false,
    companyAccess: false,
    staffAccess: true,
    remarks: null,
  },
  {
    permissionGroup: 'Services',
    description: null,
    name: 'Audit Service',
    useFlag: true,
    approveFlag: false,
    individualAccess: false,
    companyAccess: false,
    staffAccess: true,
    remarks: null,
  },
  {
    permissionGroup: 'Reviews',
    description: null,
    name: 'Create Review',
    useFlag: true,
    approveFlag: false,
    individualAccess: false,
    companyAccess: false,
    staffAccess: true,
    remarks: null,
  },
  {
    permissionGroup: 'Reviews',
    description: null,
    name: 'Read Review',
    useFlag: true,
    approveFlag: false,
    individualAccess: false,
    companyAccess: false,
    staffAccess: true,
    remarks: null,
  },
  {
    permissionGroup: 'Reviews',
    description: null,
    name: 'Update Review',
    useFlag: true,
    approveFlag: false,
    individualAccess: false,
    companyAccess: false,
    staffAccess: true,
    remarks: null,
  },
  {
    permissionGroup: 'Reviews',
    description: null,
    name: 'Delete Review',
    useFlag: true,
    approveFlag: false,
    individualAccess: false,
    companyAccess: false,
    staffAccess: true,
    remarks: null,
  },
  {
    permissionGroup: 'Reviews',
    description: null,
    name: 'Export Review',
    useFlag: true,
    approveFlag: false,
    individualAccess: false,
    companyAccess: false,
    staffAccess: true,
    remarks: null,
  },
  {
    permissionGroup: 'Reviews',
    description: null,
    name: 'Audit Review',
    useFlag: true,
    approveFlag: false,
    individualAccess: false,
    companyAccess: false,
    staffAccess: true,
    remarks: null,
  },
  {
    permissionGroup: 'Auctions',
    description: null,
    name: 'Create Auction',
    useFlag: true,
    approveFlag: false,
    individualAccess: false,
    companyAccess: false,
    staffAccess: true,
    remarks: null,
  },
  {
    permissionGroup: 'Auctions',
    description: null,
    name: 'Read Auction',
    useFlag: true,
    approveFlag: false,
    individualAccess: false,
    companyAccess: false,
    staffAccess: true,
    remarks: null,
  },
  {
    permissionGroup: 'Auctions',
    description: null,
    name: 'Update Auction',
    useFlag: true,
    approveFlag: false,
    individualAccess: false,
    companyAccess: false,
    staffAccess: true,
    remarks: null,
  },
  {
    permissionGroup: 'Auctions',
    description: null,
    name: 'Delete Auction',
    useFlag: true,
    approveFlag: false,
    individualAccess: false,
    companyAccess: false,
    staffAccess: true,
    remarks: null,
  },
  {
    permissionGroup: 'Auctions',
    description: null,
    name: 'Export Auction',
    useFlag: true,
    approveFlag: false,
    individualAccess: false,
    companyAccess: false,
    staffAccess: true,
    remarks: null,
  },
  {
    permissionGroup: 'Auctions',
    description: null,
    name: 'Audit Auction',
    useFlag: true,
    approveFlag: false,
    individualAccess: false,
    companyAccess: false,
    staffAccess: true,
    remarks: null,
  },
  {
    permissionGroup: 'Issues Categories',
    description: null,
    name: 'Create Issues Categories',
    useFlag: true,
    approveFlag: false,
    individualAccess: false,
    companyAccess: false,
    staffAccess: true,
    remarks: null,
  },
  {
    permissionGroup: 'Issues Categories',
    description: null,
    name: 'Read Issues Categories',
    useFlag: true,
    approveFlag: false,
    individualAccess: false,
    companyAccess: false,
    staffAccess: true,
    remarks: null,
  },
  {
    permissionGroup: 'Issues Categories',
    description: null,
    name: 'Update Issues Categories',
    useFlag: true,
    approveFlag: false,
    individualAccess: false,
    companyAccess: false,
    staffAccess: true,
    remarks: null,
  },
  {
    permissionGroup: 'Issues Categories',
    description: null,
    name: 'Delete Issues Categories',
    useFlag: true,
    approveFlag: false,
    individualAccess: false,
    companyAccess: false,
    staffAccess: true,
    remarks: null,
  },
  {
    permissionGroup: 'Issues Categories',
    description: null,
    name: 'Export Issues Categories',
    useFlag: true,
    approveFlag: false,
    individualAccess: false,
    companyAccess: false,
    staffAccess: true,
    remarks: null,
  },
  {
    permissionGroup: 'Issues Categories',
    description: null,
    name: 'Audit Issues Categories',
    useFlag: true,
    approveFlag: false,
    individualAccess: false,
    companyAccess: false,
    staffAccess: true,
    remarks: null,
  },
  {
    permissionGroup: 'Support Tickets',
    description: null,
    name: 'Create Support Tickets',
    useFlag: true,
    approveFlag: false,
    individualAccess: false,
    companyAccess: false,
    staffAccess: true,
    remarks: null,
  },
  {
    permissionGroup: 'Support Tickets',
    description: null,
    name: 'Read Support Tickets',
    useFlag: true,
    approveFlag: false,
    individualAccess: false,
    companyAccess: false,
    staffAccess: true,
    remarks: null,
  },
  {
    permissionGroup: 'Support Tickets',
    description: null,
    name: 'Update Support Tickets',
    useFlag: true,
    approveFlag: false,
    individualAccess: false,
    companyAccess: false,
    staffAccess: true,
    remarks: null,
  },
  {
    permissionGroup: 'Support Tickets',
    description: null,
    name: 'Delete Support Tickets',
    useFlag: true,
    approveFlag: false,
    individualAccess: false,
    companyAccess: false,
    staffAccess: true,
    remarks: null,
  },
  {
    permissionGroup: 'Support Tickets',
    description: null,
    name: 'Export Support Tickets',
    useFlag: true,
    approveFlag: false,
    individualAccess: false,
    companyAccess: false,
    staffAccess: true,
    remarks: null,
  },
  {
    permissionGroup: 'Support Tickets',
    description: null,
    name: 'Audit Support Tickets',
    useFlag: true,
    approveFlag: false,
    individualAccess: false,
    companyAccess: false,
    staffAccess: true,
    remarks: null,
  },
  {
    permissionGroup: 'Listing Type & Attributes',
    description: 'View Listing Types',
    name: 'View Listing Types',
    useFlag: true,
    approveFlag: false,
    individualAccess: false,
    companyAccess: false,
    staffAccess: true,
    remarks: null,
  },
  {
    permissionGroup: 'Listing Type & Attributes',
    description: 'View Attributes',
    name: 'View Attributes',
    useFlag: true,
    approveFlag: false,
    individualAccess: false,
    companyAccess: false,
    staffAccess: true,
    remarks: null,
  },
  {
    permissionGroup: 'Listing Type & Attributes',
    description: 'Create Listing Types',
    name: 'Create Listing Types',
    useFlag: true,
    approveFlag: false,
    individualAccess: false,
    companyAccess: false,
    staffAccess: true,
    remarks: null,
  },
  {
    permissionGroup: 'Listing Type & Attributes',
    description: 'Create Attributes',
    name: 'Create Attributes',
    useFlag: true,
    approveFlag: false,
    individualAccess: false,
    companyAccess: false,
    staffAccess: true,
    remarks: null,
  },
  {
    permissionGroup: 'Listing Type & Attributes',
    description: 'Edit Listing Types',
    name: 'Edit Listing Types',
    useFlag: true,
    approveFlag: false,
    individualAccess: false,
    companyAccess: false,
    staffAccess: true,
    remarks: null,
  },
  {
    permissionGroup: 'Listing Type & Attributes',
    description: 'Edit Attributes',
    name: 'Edit Attributes',
    useFlag: true,
    approveFlag: false,
    individualAccess: false,
    companyAccess: false,
    staffAccess: true,
    remarks: null,
  },
  {
    permissionGroup: 'Listing Type & Attributes',
    description: 'Delete Listing Types',
    name: 'Delete Listing Types',
    useFlag: true,
    approveFlag: false,
    individualAccess: false,
    companyAccess: false,
    staffAccess: true,
    remarks: null,
  },
  {
    permissionGroup: 'Listing Type & Attributes',
    description: 'Delete Attributes',
    name: 'Delete Attributes',
    useFlag: true,
    approveFlag: false,
    individualAccess: false,
    companyAccess: false,
    staffAccess: true,
    remarks: null,
  },
  {
    permissionGroup: 'Listing Type & Attributes',
    description: 'Export Listing Types',
    name: 'Export Listing Types',
    useFlag: true,
    approveFlag: false,
    individualAccess: false,
    companyAccess: false,
    staffAccess: true,
    remarks: null,
  },
  {
    permissionGroup: 'Listing Type & Attributes',
    description: 'Export Attributes',
    name: 'Export Attributes',
    useFlag: true,
    approveFlag: false,
    individualAccess: false,
    companyAccess: false,
    staffAccess: true,
    remarks: null,
  },
  {
    permissionGroup: 'Listing Type & Attributes',
    description: 'View Listing Types Audit Trail',
    name: 'View Listing Types Audit Trail',
    useFlag: true,
    approveFlag: false,
    individualAccess: false,
    companyAccess: false,
    staffAccess: true,
    remarks: null,
  },
  {
    permissionGroup: 'Listing Type & Attributes',
    description: 'View Atrributes Audit Trail',
    name: 'View Atrributes Audit Trail',
    useFlag: true,
    approveFlag: false,
    individualAccess: false,
    companyAccess: false,
    staffAccess: true,
    remarks: null,
  },
];
