/*
 * Copyright (c) 2024, Waseet LLC. All rights reserved.
 * For license. See license.txt
 */

export const permissionFactory = [
  {
    permissionGroup: 'User Management',
    description: 'Create Own User',
    name: 'Create User',
    useFlag: true,
    approveFlag: true,
    individualAccess: false,
    companyAccess: true,
    staffAccess: true,
    ramark:
      'This is a feature to enable organizations to create their own users where user admin is allowed.',
  },
  {
    permissionGroup: 'User Management',
    description: 'Edit Own User Details',
    name: 'Edit User',
    useFlag: true,
    approveFlag: true,
    individualAccess: false,
    companyAccess: true,
    staffAccess: true,
  },
  {
    permissionGroup: 'User Management',
    description: 'Delete Own User',
    name: 'Delete User',
    useFlag: true,
    approveFlag: true,
    individualAccess: false,
    companyAccess: true,
    staffAccess: true,
  },
  {
    permissionGroup: 'User Management',
    description: 'Edit Own User Status',
    name: 'Edit User Status',
    useFlag: true,
    approveFlag: true,
    individualAccess: false,
    companyAccess: true,
    staffAccess: true,
    ramark:
      'This is a feature to enable organizations to edit the status of a user (e.g. Activated  Blocked  etc...)',
  },
  {
    permissionGroup: 'User Management',
    description: 'Reset Password',
    name: 'Reset Password',
    useFlag: true,
    approveFlag: false,
    staffAccess: true,
  },
  {
    permissionGroup: 'User Management',
    description: 'View User Audit Trail',
    name: 'View User Audit Trail',
    useFlag: true,
    approveFlag: false,
    individualAccess: false,
    companyAccess: false,
    staffAccess: true,
  },
  {
    permissionGroup: 'User Management',
    description: 'Read View User information',
    name: 'View User',
    useFlag: true,
    staffAccess: true,
  },
  {
    permissionGroup: 'User Management',
    description: 'Export Users Information',
    name: 'Export Users Information',
    useFlag: true,
    staffAccess: true,
  },
  {
    permissionGroup: 'Dashboard',
    description: 'Listings Funnel',
    name: 'Listings Funnel',
    useFlag: true,
    staffAccess: true,
  },
  {
    permissionGroup: 'Dashboard',
    description: 'Revenue Card',
    name: 'Revenue Card',
    useFlag: true,
    staffAccess: true,
  },
  {
    permissionGroup: 'Dashboard',
    description: 'Users Funnel',
    name: 'Users Funnel',
    useFlag: true,
    staffAccess: true,
  },
  {
    permissionGroup: 'Dashboard',
    description: 'Users Demgraphics',
    name: 'Users Demgraphics',
    useFlag: true,
    staffAccess: true,
  },
  {
    permissionGroup: 'Dashboard',
    description: 'Saii Card',
    name: 'Saii Card',
    useFlag: true,
    staffAccess: true,
  },
  {
    permissionGroup: 'Dashboard',
    description: 'Support Response Card',
    name: 'Support Response Card',
    useFlag: true,
    staffAccess: true,
  },
  {
    permissionGroup: 'Roles',
    description: 'View Roles',
    name: 'View Roles',
    useFlag: true,
    staffAccess: true,
  },
  {
    permissionGroup: 'Roles',
    description: 'Create Roles',
    name: 'Create Roles',
    useFlag: true,
    staffAccess: true,
  },
  {
    permissionGroup: 'Roles',
    description: 'Edit Roles',
    name: 'Edit Roles',
    useFlag: true,
    staffAccess: true,
  },
  {
    permissionGroup: 'Roles',
    description: 'Delete Role',
    name: 'Delete Role',
    useFlag: true,
    staffAccess: true,
  },
  {
    permissionGroup: 'Roles',
    description: 'Export Roles',
    name: 'Export Roles',
    useFlag: true,
    staffAccess: true,
  },
  {
    permissionGroup: 'Roles',
    description: 'View Roles Audit Trail',
    name: 'View Roles Audit Trail',
    useFlag: true,
    staffAccess: true,
  },
  {
    permissionGroup: 'Listing Type & Attributes',
    description: 'View Listing Types',
    name: 'View Listing Types',
    useFlag: true,
    staffAccess: true,
  },
  {
    permissionGroup: 'Listing Type & Attributes',
    description: 'View Attributes',
    name: 'View Attributes',
    useFlag: true,
    staffAccess: true,
  },
  {
    permissionGroup: 'Listing Type & Attributes',
    description: 'Create Listing Types',
    name: 'Create Listing Types',
    useFlag: true,
    staffAccess: true,
  },
  {
    permissionGroup: 'Listing Type & Attributes',
    description: 'Create Attributes',
    name: 'Create Attributes',
    useFlag: true,
    staffAccess: true,
  },
  {
    permissionGroup: 'Listing Type & Attributes',
    description: 'Edit Listing Types',
    name: 'Edit Listing Types',
    useFlag: true,
    staffAccess: true,
  },
  {
    permissionGroup: 'Listing Type & Attributes',
    description: 'Edit Attributes',
    name: 'Edit Attributes',
    useFlag: true,
    staffAccess: true,
  },
  {
    permissionGroup: 'Listing Type & Attributes',
    description: 'Delete Listing Types',
    name: 'Delete Listing Types',
    useFlag: true,
    staffAccess: true,
  },
  {
    permissionGroup: 'Listing Type & Attributes',
    description: 'Delete Attributes',
    name: 'Delete Attributes',
    useFlag: true,
    staffAccess: true,
  },
  {
    permissionGroup: 'Listing Type & Attributes',
    description: 'Export Listing Types',
    name: 'Export Listing Types',
    useFlag: true,
    staffAccess: true,
  },
  {
    permissionGroup: 'Listing Type & Attributes',
    description: 'Export Attributes',
    name: 'Export Attributes',
    useFlag: true,
    staffAccess: true,
  },
  {
    permissionGroup: 'Listing Type & Attributes',
    description: 'View Listing Types Audit Trail',
    name: 'View Listing Types Audit Trail',
    useFlag: true,
    staffAccess: true,
  },
  {
    permissionGroup: 'Listing Type & Attributes',
    description: 'View Atrributes Audit Trail',
    name: 'View Atrributes Audit Trail',
    useFlag: true,
    staffAccess: true,
  },
  {
    permissionGroup: 'System Settings',
    description: 'View System Settings',
    name: 'View System Settings',
    useFlag: true,
    staffAccess: true,
  },
  {
    permissionGroup: 'System Settings',
    description: 'Edit System Settings',
    name: 'Edit System Settings',
    useFlag: true,
    staffAccess: true,
  },
  {
    permissionGroup: 'System Settings',
    description: 'View System Settings Audit Trail',
    name: 'View System Settings Audit Trail',
    useFlag: true,
    staffAccess: true,
  },
  {
    permissionGroup: 'Coupons',
    description: 'View Coupons',
    name: 'View Coupons',
    useFlag: true,
    staffAccess: true,
  },
  {
    permissionGroup: 'Coupons',
    description: 'Create Coupons ',
    name: 'Create Coupons ',
    useFlag: true,
    staffAccess: true,
  },
  {
    permissionGroup: 'Coupons',
    description: 'Edit Coupons',
    name: 'Edit Coupons',
    useFlag: true,
    staffAccess: true,
  },
  {
    permissionGroup: 'Coupons',
    description: 'Export Coupons',
    name: 'Export Coupons',
    useFlag: true,
    staffAccess: true,
  },
  {
    permissionGroup: 'Coupons',
    description: 'Delete Coupons',
    name: 'Delete Coupons',
    useFlag: true,
    staffAccess: true,
  },
  {
    permissionGroup: 'Coupons',
    description: 'View Coupons Audit Trail',
    name: 'View Coupons Audit Trail',
    useFlag: true,
    staffAccess: true,
  },
  {
    permissionGroup: 'Coupons',
    description: 'Change Coupon Status DeactivateReactivate',
    name: 'Change Coupon Status DeactivateReactivate',
    useFlag: true,
    staffAccess: true,
  },
  {
    permissionGroup: 'CMS',
    description: 'Create Content',
    name: 'Create Content',
    useFlag: true,
    staffAccess: true,
  },
  {
    permissionGroup: 'CMS',
    description: 'Edit Content',
    name: 'Edit Content',
    useFlag: true,
    staffAccess: true,
  },
  {
    permissionGroup: 'CMS',
    description: 'View CMS',
    name: 'View CMS',
    useFlag: true,
    staffAccess: true,
  },
  {
    permissionGroup: 'CMS',
    description: 'Delete Content',
    name: 'Delete Content',
    useFlag: true,
    staffAccess: true,
  },
  {
    permissionGroup: 'CMS',
    description: 'View CMS Audit Trail',
    name: 'View CMS Audit Trail',
    useFlag: true,
    staffAccess: true,
  },
  {
    permissionGroup: 'CMS',
    description: 'Change Content Status Published - Un Published',
    name: 'Change Content Status Published - Un Published',
    useFlag: true,
    staffAccess: true,
  },
  {
    permissionGroup: 'CMS Categories',
    description: 'View CMS Categories',
    name: 'View CMS Categories',
    useFlag: true,
    staffAccess: true,
  },
  {
    permissionGroup: 'CMS Categories',
    description: 'Create Categories',
    name: 'Create Categories',
    useFlag: true,
    staffAccess: true,
  },
  {
    permissionGroup: 'CMS Categories',
    description: 'Edit Categories',
    name: 'Edit Categories',
    useFlag: true,
    staffAccess: true,
  },
  {
    permissionGroup: 'CMS Categories',
    description: 'Delete Categories',
    name: 'Delete Categories',
    useFlag: true,
    staffAccess: true,
  },
  {
    permissionGroup: 'CMS Categories',
    description: 'View Categories Audit Trail',
    name: 'View Categories Audit Trail',
    useFlag: true,
    staffAccess: true,
  },
  {
    permissionGroup: 'Service Provider Applications',
    description: 'View Service Provider Applications',
    name: 'View Service Provider Applications',
    useFlag: true,
    staffAccess: true,
  },
  {
    permissionGroup: 'Service Provider Applications',
    description: 'Export Applications',
    name: 'Export Applications',
    useFlag: true,
    staffAccess: true,
  },
  {
    permissionGroup: 'Service Provider Applications',
    description: 'View Applications Audit Trail ',
    name: 'View Applications Audit Trail ',
    useFlag: true,
    staffAccess: true,
  },
  {
    permissionGroup: 'Service Provider Applications',
    description: 'Approve  Decline Applications',
    name: 'Approve  Decline Applications',
    useFlag: true,
    staffAccess: true,
  },
  {
    permissionGroup: 'Issues Categories',
    description: 'Read',
    name: 'Read',
    useFlag: true,
    staffAccess: true,
  },
  {
    permissionGroup: 'Issues Categories',
    description: 'Create',
    name: 'Create',
    useFlag: true,
    staffAccess: true,
  },
  {
    permissionGroup: 'Issues Categories',
    description: 'Delete',
    name: 'Delete',
    useFlag: true,
    staffAccess: true,
  },
  {
    permissionGroup: 'Issues Categories',
    description: 'View Audit Trail',
    name: 'View Audit Trail',
    useFlag: true,
    staffAccess: true,
  },
  {
    permissionGroup: 'Support Tickets',
    description: 'Read',
    name: 'Read',
    useFlag: true,
    staffAccess: true,
  },
  {
    permissionGroup: 'Support Tickets',
    description: 'Edit',
    name: 'Edit',
    useFlag: true,
    staffAccess: true,
  },
  {
    permissionGroup: 'Support Tickets',
    description: 'Export',
    name: 'Export',
    useFlag: true,
    staffAccess: true,
  },
  {
    permissionGroup: 'Support Tickets',
    description: 'Change Status Open , Closed, etc',
    name: 'Change Status Open , Closed, etc',
    useFlag: true,
    staffAccess: true,
  },
  {
    permissionGroup: 'Support Tickets',
    description: 'View Audit Trail',
    name: 'View Audit Trail',
    useFlag: true,
    staffAccess: true,
  },
  {
    permissionGroup: 'Response Templates',
    description: 'Read',
    name: 'Read',
    useFlag: true,
    staffAccess: true,
  },
  {
    permissionGroup: 'Response Templates',
    description: 'Edit',
    name: 'Edit',
    useFlag: true,
    staffAccess: true,
  },
  {
    permissionGroup: 'Response Templates',
    description: 'Create',
    name: 'Create',
    useFlag: true,
    staffAccess: true,
  },
  {
    permissionGroup: 'Response Templates',
    description: 'Delete',
    name: 'Delete',
    useFlag: true,
    staffAccess: true,
  },
  {
    permissionGroup: 'Response Templates',
    description: 'View Audit Trail',
    name: 'View Audit Trail',
    useFlag: true,
    staffAccess: true,
  },
  {
    permissionGroup: 'Knowledge Base',
    description: 'Read',
    name: 'Read',
    useFlag: true,
    staffAccess: true,
  },
  {
    permissionGroup: 'Knowledge Base',
    description: 'Create',
    name: 'Create',
    useFlag: true,
    staffAccess: true,
  },
  {
    permissionGroup: 'Knowledge Base',
    description: 'Edit',
    name: 'Edit',
    useFlag: true,
    staffAccess: true,
  },
  {
    permissionGroup: 'Knowledge Base',
    description: 'Delete',
    name: 'Delete',
    useFlag: true,
    staffAccess: true,
  },
  {
    permissionGroup: 'Knowledge Base',
    description: 'View Audit Trail',
    name: 'View Audit Trail',
    useFlag: true,
    staffAccess: true,
  },
  {
    permissionGroup: 'Knowledge Base',
    description: 'Publish  Unpublish',
    name: 'Publish  Unpublish',
    useFlag: true,
    staffAccess: true,
  },
  {
    permissionGroup: 'KB Categories',
    description: 'Read',
    name: 'Read',
    useFlag: true,
    staffAccess: true,
  },
  {
    permissionGroup: 'KB Categories',
    description: 'Create',
    name: 'Create',
    useFlag: true,
    staffAccess: true,
  },
  {
    permissionGroup: 'KB Categories',
    description: 'Edit',
    name: 'Edit',
    useFlag: true,
    staffAccess: true,
  },
  {
    permissionGroup: 'KB Categories',
    description: 'Delete',
    name: 'Delete',
    useFlag: true,
    staffAccess: true,
  },
  {
    permissionGroup: 'KB Categories',
    description: 'View Audit Trail',
    name: 'View Audit Trail',
    useFlag: true,
    staffAccess: true,
  },
  {
    permissionGroup: 'Listings',
    description: 'View Listing Details',
    name: 'View Listing Details',
    useFlag: true,
    staffAccess: true,
  },
  {
    permissionGroup: 'Listings',
    description: 'Create',
    name: 'Create',
    useFlag: true,
    staffAccess: true,
  },
  {
    permissionGroup: 'Listings',
    description: 'Edit',
    name: 'Edit',
    useFlag: true,
    staffAccess: true,
  },
  {
    permissionGroup: 'Listings',
    description: 'Delete',
    name: 'Delete',
    useFlag: true,
    staffAccess: true,
  },
  {
    permissionGroup: 'Listings',
    description: 'Export',
    name: 'Export',
    useFlag: true,
    staffAccess: true,
  },
  {
    permissionGroup: 'Listings',
    description: 'View Audit Trail',
    name: 'View Audit Trail',
    useFlag: true,
    staffAccess: true,
  },
  {
    permissionGroup: 'Listings',
    description: 'Multi Actions Stop Promotions, Deactivate, etc',
    name: 'Multi Actions Stop Promotions, Deactivate, etc',
    useFlag: true,
    staffAccess: true,
  },
  {
    permissionGroup: 'Reviews',
    description: 'Read',
    name: 'Read',
    useFlag: true,
    staffAccess: true,
  },
  {
    permissionGroup: 'Reviews',
    description: 'Export',
    name: 'Export',
    useFlag: true,
    staffAccess: true,
  },
  {
    permissionGroup: 'Reports',
    description: 'Read',
    name: 'Read',
    useFlag: true,
    staffAccess: true,
  },
  {
    permissionGroup: 'Reports',
    description: 'Create',
    name: 'Create',
    useFlag: true,
    staffAccess: true,
  },
  {
    permissionGroup: 'Reports',
    description: 'Export',
    name: 'Export',
    useFlag: true,
    staffAccess: true,
  },
  {
    permissionGroup: 'Workflow',
    description: 'Read',
    name: 'Read',
    useFlag: true,
    staffAccess: true,
  },
  {
    permissionGroup: 'Workflow',
    description: 'Create',
    name: 'Create',
    useFlag: true,
    staffAccess: true,
  },
  {
    permissionGroup: 'Workflow',
    description: 'Edit',
    name: 'Edit',
    useFlag: true,
    staffAccess: true,
  },
  {
    permissionGroup: 'Workflow',
    description: 'Delete',
    name: 'Delete',
    useFlag: true,
    staffAccess: true,
  },
  {
    permissionGroup: 'Workflow',
    description: 'Export',
    name: 'Export',
    useFlag: true,
    staffAccess: true,
  },
  {
    permissionGroup: 'Workflow',
    description: 'View Audit Trail',
    name: 'View Audit Trail',
    useFlag: true,
    staffAccess: true,
  },
  {
    permissionGroup: 'Workflow',
    description: 'Status Deactivate  Reactivate',
    name: 'Status Deactivate  Reactivate',
    useFlag: true,
    staffAccess: true,
  },
  {
    permissionGroup: 'Auctions',
    description: 'Read',
    name: 'Read',
    useFlag: true,
    staffAccess: true,
  },
  {
    permissionGroup: 'Auctions',
    description: 'Create',
    name: 'Create',
    useFlag: true,
    staffAccess: true,
  },
  {
    permissionGroup: 'Auctions',
    description: 'Edit',
    name: 'Edit',
    useFlag: true,
    staffAccess: true,
  },
  {
    permissionGroup: 'Auctions',
    description: 'Delete',
    name: 'Delete',
    useFlag: true,
    staffAccess: true,
  },
  {
    permissionGroup: 'Auctions',
    description: 'Export',
    name: 'Export',
    useFlag: true,
    staffAccess: true,
  },
  {
    permissionGroup: 'Auctions',
    description: 'View Audit Trail',
    name: 'View Audit Trail',
    useFlag: true,
    staffAccess: true,
  },
  {
    permissionGroup: 'Auctions',
    description: 'Status Deactivate  Reactivate',
    name: 'Status Deactivate  Reactivate',
    useFlag: true,
    staffAccess: true,
  },
  {
    permissionGroup: 'Services',
    description: 'Read',
    name: 'Read',
    useFlag: true,
    staffAccess: true,
  },
  {
    permissionGroup: 'Services',
    description: 'Create',
    name: 'Create',
    useFlag: true,
    staffAccess: true,
  },
  {
    permissionGroup: 'Services',
    description: 'Edit',
    name: 'Edit',
    useFlag: true,
    staffAccess: true,
  },
  {
    permissionGroup: 'Services',
    description: 'Delete',
    name: 'Delete',
    useFlag: true,
    staffAccess: true,
  },
  {
    permissionGroup: 'Services',
    description: 'Export',
    name: 'Export',
    useFlag: true,
    staffAccess: true,
  },
  {
    permissionGroup: 'Services',
    description: 'View Audit Trail',
    name: 'View Audit Trail',
    useFlag: true,
    staffAccess: true,
  },
  {
    permissionGroup: 'Services',
    description: 'Status Deactivate  Reactivate',
    name: 'Status Deactivate  Reactivate',
    useFlag: true,
    staffAccess: true,
  },
];
