/*
 * Copyright (c) 2024, Waseet LLC. All rights reserved.
 * For license. See license.txt
 */

//To update permission, delete all permisions in the table First
export const permissionFactory = [
  {
    category: 'Auctions',
    functionDescription: 'Read',
    englishLabel: 'Read',
    arabicLabel: null,
    useFlag: true,
    approveFlag: null,
    individualAccess: null,
    companyAccess: null,
    staffAccess: true,
    remarks: null,
  },

  {
    category: 'Auctions',
    functionDescription: 'Create',
    englishLabel: 'Create',
    arabicLabel: null,
    useFlag: true,
    approveFlag: null,
    individualAccess: null,
    companyAccess: null,
    staffAccess: true,
    remarks: null,
  },
  {
    category: 'Auctions',
    functionDescription: 'Edit',
    englishLabel: 'Edit',
    arabicLabel: null,
    useFlag: true,
    approveFlag: null,
    individualAccess: null,
    companyAccess: null,
    staffAccess: true,
    remarks: null,
  },
  {
    category: 'Auctions',
    functionDescription: 'Delete',
    englishLabel: 'Delete',
    arabicLabel: null,
    useFlag: true,
    approveFlag: null,
    individualAccess: null,
    companyAccess: null,
    staffAccess: true,
    remarks: null,
  },
  {
    category: 'Auctions',
    functionDescription: 'Export',
    englishLabel: 'Export',
    arabicLabel: null,
    useFlag: true,
    approveFlag: null,
    individualAccess: null,
    companyAccess: null,
    staffAccess: true,
    remarks: null,
  },
  {
    category: 'Auctions',
    functionDescription: 'View Audit Trail',
    englishLabel: 'View Audit Trail',
    arabicLabel: null,
    useFlag: true,
    approveFlag: null,
    individualAccess: null,
    companyAccess: null,
    staffAccess: true,
    remarks: null,
  },
  {
    category: 'Auctions',
    functionDescription: 'Status "Deactivate / Reactivate"',
    englishLabel: 'Status "Deactivate / Reactivate"',
    arabicLabel: null,
    useFlag: true,
    approveFlag: null,
    individualAccess: null,
    companyAccess: null,
    staffAccess: true,
    remarks: null,
  },
  {
    category: 'CMS',
    functionDescription: 'Create Content',
    englishLabel: 'Create Content',
    arabicLabel: null,
    useFlag: true,
    approveFlag: null,
    individualAccess: null,
    companyAccess: null,
    staffAccess: true,
    remarks: null,
  },
  {
    category: 'CMS',
    functionDescription: 'Edit Content',
    englishLabel: 'Edit Content',
    arabicLabel: null,
    useFlag: true,
    approveFlag: null,
    individualAccess: null,
    companyAccess: null,
    staffAccess: true,
    remarks: null,
  },
  {
    category: 'CMS',
    functionDescription: 'View CMS',
    englishLabel: 'View CMS',
    arabicLabel: null,
    useFlag: true,
    approveFlag: null,
    individualAccess: null,
    companyAccess: null,
    staffAccess: true,
    remarks: null,
  },
  {
    category: 'CMS',
    functionDescription: 'Delete Content',
    englishLabel: 'Delete Content',
    arabicLabel: null,
    useFlag: true,
    approveFlag: null,
    individualAccess: null,
    companyAccess: null,
    staffAccess: true,
    remarks: null,
  },
  {
    category: 'CMS',
    functionDescription: 'View CMS Audit Trail',
    englishLabel: 'View CMS Audit Trail',
    arabicLabel: null,
    useFlag: true,
    approveFlag: null,
    individualAccess: null,
    companyAccess: null,
    staffAccess: true,
    remarks: null,
  },
  {
    category: 'CMS',
    functionDescription: 'Change Content Status " Published - Un Published"',
    englishLabel: 'Change Content Status " Published - Un Published"',
    arabicLabel: null,
    useFlag: true,
    approveFlag: null,
    individualAccess: null,
    companyAccess: null,
    staffAccess: true,
    remarks: null,
  },

  {
    category: 'CMS Categories',
    functionDescription: 'View CMS Categories',
    englishLabel: 'View CMS Categories',
    arabicLabel: null,
    useFlag: true,
    approveFlag: null,
    individualAccess: null,
    companyAccess: null,
    staffAccess: true,
    remarks: null,
  },

  {
    category: 'CMS Categories',
    functionDescription: 'Create Categories',
    englishLabel: 'Create Categories',
    arabicLabel: null,
    useFlag: true,
    approveFlag: null,
    individualAccess: null,
    companyAccess: null,
    staffAccess: true,
    remarks: null,
  },

  {
    category: 'CMS Categories',
    functionDescription: 'Edit Categories',
    englishLabel: 'Edit Categories',
    arabicLabel: null,
    useFlag: true,
    approveFlag: null,
    individualAccess: null,
    companyAccess: null,
    staffAccess: true,
    remarks: null,
  },
  {
    category: 'CMS Categories',
    functionDescription: 'Delete Categories',
    englishLabel: 'Delete Categories',
    arabicLabel: null,
    useFlag: true,
    approveFlag: null,
    individualAccess: null,
    companyAccess: null,
    staffAccess: true,
    remarks: null,
  },
  {
    category: 'CMS Categories',
    functionDescription: 'View Categories Audit Trail',
    englishLabel: 'View Categories Audit Trail',
    arabicLabel: null,
    useFlag: true,
    approveFlag: null,
    individualAccess: null,
    companyAccess: null,
    staffAccess: true,
    remarks: null,
  },
  {
    category: 'Coupons',
    functionDescription: 'View Coupons',
    englishLabel: 'View Coupons',
    arabicLabel: null,
    useFlag: true,
    approveFlag: null,
    individualAccess: null,
    companyAccess: null,
    staffAccess: true,
    remarks: null,
  },
  {
    category: 'Coupons',
    functionDescription: 'Create Coupons',
    englishLabel: 'Create Coupons',
    arabicLabel: null,
    useFlag: true,
    approveFlag: null,
    individualAccess: null,
    companyAccess: null,
    staffAccess: true,
    remarks: null,
  },

  {
    category: 'Coupons',
    functionDescription: 'Edit Coupons',
    englishLabel: 'Edit Coupons',
    arabicLabel: null,
    useFlag: true,
    approveFlag: null,
    individualAccess: null,
    companyAccess: null,
    staffAccess: true,
    remarks: null,
  },

  {
    category: 'Coupons',
    functionDescription: 'Export Coupons',
    englishLabel: 'Export Coupons',
    arabicLabel: null,
    useFlag: true,
    approveFlag: null,
    individualAccess: null,
    companyAccess: null,
    staffAccess: true,
    remarks: null,
  },
  {
    category: 'Coupons',
    functionDescription: 'Delete Coupons',
    englishLabel: 'Delete Coupons',
    arabicLabel: null,
    useFlag: true,
    approveFlag: null,
    individualAccess: null,
    companyAccess: null,
    staffAccess: true,
    remarks: null,
  },
  {
    category: 'Coupons',
    functionDescription: 'View Coupons Audit Trail',
    englishLabel: 'View Coupons Audit Trail',
    arabicLabel: null,
    useFlag: true,
    approveFlag: null,
    individualAccess: null,
    companyAccess: null,
    staffAccess: true,
    remarks: null,
  },
  {
    category: 'Coupons',
    functionDescription: 'Change Coupon Status "Deactivate/Reactivate"',
    englishLabel: 'Change Coupon Status "Deactivate/Reactivate"',
    arabicLabel: null,
    useFlag: true,
    approveFlag: null,
    individualAccess: null,
    companyAccess: null,
    staffAccess: true,
    remarks: null,
  },
  {
    category: 'Dashboard',
    functionDescription: 'Listings Funnel',
    englishLabel: 'Listings Funnel',
    arabicLabel: null,
    useFlag: true,
    approveFlag: null,
    individualAccess: null,
    companyAccess: null,
    staffAccess: true,
    remarks: null,
  },
  {
    category: 'Dashboard',
    functionDescription: 'Revenue Card',
    englishLabel: 'Revenue Card',
    arabicLabel: null,
    useFlag: true,
    approveFlag: null,
    individualAccess: null,
    companyAccess: null,
    staffAccess: true,
    remarks: null,
  },
  {
    category: 'Dashboard',
    functionDescription: 'Users Funnel',
    englishLabel: 'Users Funnel',
    arabicLabel: null,
    useFlag: true,
    approveFlag: null,
    individualAccess: null,
    companyAccess: null,
    staffAccess: true,
    remarks: null,
  },
  {
    category: 'Dashboard',
    functionDescription: 'Users Demgraphics',
    englishLabel: 'Users Demgraphics',
    arabicLabel: null,
    useFlag: true,
    approveFlag: null,
    individualAccess: null,
    companyAccess: null,
    staffAccess: true,
    remarks: null,
  },
  {
    category: 'Dashboard',
    functionDescription: 'Saii Card',
    englishLabel: 'Saii Card',
    arabicLabel: null,
    useFlag: true,
    approveFlag: null,
    individualAccess: null,
    companyAccess: null,
    staffAccess: true,
    remarks: null,
  },
  {
    category: 'Dashboard',
    functionDescription: 'Support Response Card',
    englishLabel: 'Support Response Card',
    arabicLabel: null,
    useFlag: true,
    approveFlag: null,
    individualAccess: null,
    companyAccess: null,
    staffAccess: true,
    remarks: null,
  },
  {
    category: 'Issues Categories',
    functionDescription: 'Read',
    englishLabel: 'Read',
    arabicLabel: null,
    useFlag: true,
    approveFlag: null,
    individualAccess: null,
    companyAccess: null,
    staffAccess: true,
    remarks: null,
  },
  {
    category: 'Issues Categories',
    functionDescription: 'Create',
    englishLabel: 'Create',
    arabicLabel: null,
    useFlag: true,
    approveFlag: null,
    individualAccess: null,
    companyAccess: null,
    staffAccess: true,
    remarks: null,
  },
  {
    category: 'Issues Categories',
    functionDescription: 'Delete',
    englishLabel: 'Delete',
    arabicLabel: null,
    useFlag: true,
    approveFlag: null,
    individualAccess: null,
    companyAccess: null,
    staffAccess: true,
    remarks: null,
  },
  {
    category: 'Issues Categories',
    functionDescription: 'View Audit Trail',
    englishLabel: 'View Audit Trail',
    arabicLabel: null,
    useFlag: true,
    approveFlag: null,
    individualAccess: null,
    companyAccess: null,
    staffAccess: true,
    remarks: null,
  },
  {
    category: 'KB Categories',
    functionDescription: 'Read',
    englishLabel: 'Read',
    arabicLabel: null,
    useFlag: true,
    approveFlag: null,
    individualAccess: null,
    companyAccess: null,
    staffAccess: true,
    remarks: null,
  },
  {
    category: 'KB Categories',
    functionDescription: 'Create',
    englishLabel: 'Create',
    arabicLabel: null,
    useFlag: true,
    approveFlag: null,
    individualAccess: null,
    companyAccess: null,
    staffAccess: true,
    remarks: null,
  },
  {
    category: 'KB Categories',
    functionDescription: 'Edit',
    englishLabel: 'Edit',
    arabicLabel: null,
    useFlag: true,
    approveFlag: null,
    individualAccess: null,
    companyAccess: null,
    staffAccess: true,
    remarks: null,
  },
  {
    category: 'KB Categories',
    functionDescription: 'Delete',
    englishLabel: 'Delete',
    arabicLabel: null,
    useFlag: true,
    approveFlag: null,
    individualAccess: null,
    companyAccess: null,
    staffAccess: true,
    remarks: null,
  },
  {
    category: 'KB Categories',
    functionDescription: 'View Audit Trail',
    englishLabel: 'View Audit Trail',
    arabicLabel: null,
    useFlag: true,
    approveFlag: null,
    individualAccess: null,
    companyAccess: null,
    staffAccess: true,
    remarks: null,
  },
  {
    category: 'Knowledge Base',
    functionDescription: 'Read',
    englishLabel: 'Read',
    arabicLabel: null,
    useFlag: true,
    approveFlag: null,
    individualAccess: null,
    companyAccess: null,
    staffAccess: true,
    remarks: null,
  },
  {
    category: 'Knowledge Base',
    functionDescription: 'Create',
    englishLabel: 'Create',
    arabicLabel: null,
    useFlag: true,
    approveFlag: null,
    individualAccess: null,
    companyAccess: null,
    staffAccess: true,
    remarks: null,
  },
  {
    category: 'Knowledge Base',
    functionDescription: 'Edit',
    englishLabel: 'Edit',
    arabicLabel: null,
    useFlag: true,
    approveFlag: null,
    individualAccess: null,
    companyAccess: null,
    staffAccess: true,
    remarks: null,
  },
  {
    category: 'Knowledge Base',
    functionDescription: 'Delete',
    englishLabel: 'Delete',
    arabicLabel: null,
    useFlag: true,
    approveFlag: null,
    individualAccess: null,
    companyAccess: null,
    staffAccess: true,
    remarks: null,
  },
  {
    category: 'Knowledge Base',
    functionDescription: 'View Audit Trail',
    englishLabel: 'View Audit Trail',
    arabicLabel: null,
    useFlag: true,
    approveFlag: null,
    individualAccess: null,
    companyAccess: null,
    staffAccess: true,
    remarks: null,
  },
  {
    category: 'Knowledge Base',
    functionDescription: 'Publish / Unpublish',
    englishLabel: 'Publish / Unpublish',
    arabicLabel: null,
    useFlag: true,
    approveFlag: null,
    individualAccess: null,
    companyAccess: null,
    staffAccess: true,
    remarks: null,
  },
  {
    category: 'Listing Type & Attributes',
    functionDescription: 'View Listing Types',
    englishLabel: 'View Listing Types',
    arabicLabel: null,
    useFlag: true,
    approveFlag: null,
    individualAccess: null,
    companyAccess: null,
    staffAccess: true,
    remarks: null,
  },
  {
    category: 'Listing Type & Attributes',
    functionDescription: 'View Attributes',
    englishLabel: 'View Attributes',
    arabicLabel: null,
    useFlag: true,
    approveFlag: null,
    individualAccess: null,
    companyAccess: null,
    staffAccess: true,
    remarks: null,
  },
  {
    category: 'Listing Type & Attributes',
    functionDescription: 'Create Listing Types',
    englishLabel: 'Create Listing Types',
    arabicLabel: null,
    useFlag: true,
    approveFlag: null,
    individualAccess: null,
    companyAccess: null,
    staffAccess: true,
    remarks: null,
  },
  {
    category: 'Listing Type & Attributes',
    functionDescription: 'Create Attributes',
    englishLabel: 'Create Attributes',
    arabicLabel: null,
    useFlag: true,
    approveFlag: null,
    individualAccess: null,
    companyAccess: null,
    staffAccess: true,
    remarks: null,
  },
  {
    category: 'Listing Type & Attributes',
    functionDescription: 'Edit Listing Types',
    englishLabel: 'Edit Listing Types',
    arabicLabel: null,
    useFlag: true,
    approveFlag: null,
    individualAccess: null,
    companyAccess: null,
    staffAccess: true,
    remarks: null,
  },
  {
    category: 'Listing Type & Attributes',
    functionDescription: 'Edit Attributes',
    englishLabel: 'Edit Attributes',
    arabicLabel: null,
    useFlag: true,
    approveFlag: null,
    individualAccess: null,
    companyAccess: null,
    staffAccess: true,
    remarks: null,
  },
  {
    category: 'Listing Type & Attributes',
    functionDescription: 'Delete Listing Types',
    englishLabel: 'Delete Listing Types',
    arabicLabel: null,
    useFlag: true,
    approveFlag: null,
    individualAccess: null,
    companyAccess: null,
    staffAccess: true,
    remarks: null,
  },
  {
    category: 'Listing Type & Attributes',
    functionDescription: 'Delete Attributes',
    englishLabel: 'Delete Attributes',
    arabicLabel: null,
    useFlag: true,
    approveFlag: null,
    individualAccess: null,
    companyAccess: null,
    staffAccess: true,
    remarks: null,
  },

  {
    category: 'Listing Type & Attributes',
    functionDescription: 'Export Listing Types',
    englishLabel: 'Export Listing Types',
    arabicLabel: null,
    useFlag: true,
    approveFlag: null,
    individualAccess: null,
    companyAccess: null,
    staffAccess: true,
    remarks: null,
  },

  {
    category: 'Listing Type & Attributes',
    functionDescription: 'Export Attributes',
    englishLabel: 'Export Attributes',
    arabicLabel: null,
    useFlag: true,
    approveFlag: null,
    individualAccess: null,
    companyAccess: null,
    staffAccess: true,
    remarks: null,
  },
  {
    category: 'Listing Type & Attributes',
    functionDescription: 'View Listing Types Audit Trail',
    englishLabel: 'View Listing Types Audit Trail',
    arabicLabel: null,
    useFlag: true,
    approveFlag: null,
    individualAccess: null,
    companyAccess: null,
    staffAccess: true,
    remarks: null,
  },
  {
    category: 'Listing Type & Attributes',
    functionDescription: 'View Atrributes Audit Trail',
    englishLabel: 'View Atrributes Audit Trail',
    arabicLabel: null,
    useFlag: true,
    approveFlag: null,
    individualAccess: null,
    companyAccess: null,
    staffAccess: true,
    remarks: null,
  },
  {
    category: 'Listings',
    functionDescription: 'View Listing Details',
    englishLabel: 'View Listing Details',
    arabicLabel: null,
    useFlag: true,
    approveFlag: null,
    individualAccess: null,
    companyAccess: null,
    staffAccess: true,
    remarks: null,
  },
  {
    category: 'Listings',
    functionDescription: 'Create',
    englishLabel: 'Create',
    arabicLabel: null,
    useFlag: true,
    approveFlag: null,
    individualAccess: null,
    companyAccess: null,
    staffAccess: true,
    remarks: null,
  },
  {
    category: 'Listings',
    functionDescription: 'Edit',
    englishLabel: 'Edit',
    arabicLabel: null,
    useFlag: true,
    approveFlag: null,
    individualAccess: null,
    companyAccess: null,
    staffAccess: true,
    remarks: null,
  },
  {
    category: 'Listings',
    functionDescription: 'Delete',
    englishLabel: 'Delete',
    arabicLabel: null,
    useFlag: true,
    approveFlag: null,
    individualAccess: null,
    companyAccess: null,
    staffAccess: true,
    remarks: null,
  },
  {
    category: 'Listings',
    functionDescription: 'Export',
    englishLabel: 'Export',
    arabicLabel: null,
    useFlag: true,
    approveFlag: null,
    individualAccess: null,
    companyAccess: null,
    staffAccess: true,
    remarks: null,
  },
  {
    category: 'Listings',
    functionDescription: 'View Audit Trail',
    englishLabel: 'View Audit Trail',
    arabicLabel: null,
    useFlag: true,
    approveFlag: null,
    individualAccess: null,
    companyAccess: null,
    staffAccess: true,
    remarks: null,
  },
  {
    category: 'Listings',
    functionDescription: 'Multi Actions "Stop Promotions, Deactivate, etc"',
    englishLabel: 'Multi Actions "Stop Promotions, Deactivate, etc"',
    arabicLabel: null,
    useFlag: true,
    approveFlag: null,
    individualAccess: null,
    companyAccess: null,
    staffAccess: true,
    remarks: null,
  },
  {
    category: 'Reports',
    functionDescription: 'Read',
    englishLabel: 'Read',
    arabicLabel: null,
    useFlag: true,
    approveFlag: null,
    individualAccess: null,
    companyAccess: null,
    staffAccess: true,
    remarks: null,
  },
  {
    category: 'Reports',
    functionDescription: 'Create',
    englishLabel: 'Create',
    arabicLabel: null,
    useFlag: true,
    approveFlag: null,
    individualAccess: null,
    companyAccess: null,
    staffAccess: true,
    remarks: null,
  },
  {
    category: 'Reports',
    functionDescription: 'Export',
    englishLabel: 'Export',
    arabicLabel: null,
    useFlag: true,
    approveFlag: null,
    individualAccess: null,
    companyAccess: null,
    staffAccess: true,
    remarks: null,
  },
  {
    category: 'Response Templates',
    functionDescription: 'Read',
    englishLabel: 'Read',
    arabicLabel: null,
    useFlag: true,
    approveFlag: null,
    individualAccess: null,
    companyAccess: null,
    staffAccess: true,
    remarks: null,
  },
  {
    category: 'Response Templates',
    functionDescription: 'Edit',
    englishLabel: 'Edit',
    arabicLabel: null,
    useFlag: true,
    approveFlag: null,
    individualAccess: null,
    companyAccess: null,
    staffAccess: true,
    remarks: null,
  },
  {
    category: 'Response Templates',
    functionDescription: 'Create',
    englishLabel: 'Create',
    arabicLabel: null,
    useFlag: true,
    approveFlag: null,
    individualAccess: null,
    companyAccess: null,
    staffAccess: true,
    remarks: null,
  },
  {
    category: 'Response Templates',
    functionDescription: 'Delete',
    englishLabel: 'Delete',
    arabicLabel: null,
    useFlag: true,
    approveFlag: null,
    individualAccess: null,
    companyAccess: null,
    staffAccess: true,
    remarks: null,
  },
  {
    category: 'Response Templates',
    functionDescription: 'View Audit Trail',
    englishLabel: 'View Audit Trail',
    arabicLabel: null,
    useFlag: true,
    approveFlag: null,
    individualAccess: null,
    companyAccess: null,
    staffAccess: true,
    remarks: null,
  },
  {
    category: 'Reviews',
    functionDescription: 'Read',
    englishLabel: 'Read',
    arabicLabel: null,
    useFlag: true,
    approveFlag: null,
    individualAccess: null,
    companyAccess: null,
    staffAccess: true,
    remarks: null,
  },
  {
    category: 'Reviews',
    functionDescription: 'Export',
    englishLabel: 'Export',
    arabicLabel: null,
    useFlag: true,
    approveFlag: null,
    individualAccess: null,
    companyAccess: null,
    staffAccess: true,
    remarks: null,
  },
  {
    category: 'Roles',
    functionDescription: 'View Roles',
    englishLabel: 'View Roles',
    arabicLabel: null,
    useFlag: true,
    approveFlag: null,
    individualAccess: null,
    companyAccess: null,
    staffAccess: true,
    remarks: null,
  },
  {
    category: 'Roles',
    functionDescription: 'Create Roles',
    englishLabel: 'Create Roles',
    arabicLabel: null,
    useFlag: true,
    approveFlag: null,
    individualAccess: null,
    companyAccess: null,
    staffAccess: true,
    remarks: null,
  },
  {
    category: 'Roles',
    functionDescription: 'Edit Roles',
    englishLabel: 'Edit Roles',
    arabicLabel: null,
    useFlag: true,
    approveFlag: null,
    individualAccess: null,
    companyAccess: null,
    staffAccess: true,
    remarks: null,
  },
  {
    category: 'Roles',
    functionDescription: 'Delete Role',
    englishLabel: 'Delete Role',
    arabicLabel: null,
    useFlag: true,
    approveFlag: null,
    individualAccess: null,
    companyAccess: null,
    staffAccess: true,
    remarks: null,
  },
  {
    category: 'Roles',
    functionDescription: 'Export Roles',
    englishLabel: 'Export Roles',
    arabicLabel: null,
    useFlag: true,
    approveFlag: null,
    individualAccess: null,
    companyAccess: null,
    staffAccess: true,
    remarks: null,
  },
  {
    category: 'Roles',
    functionDescription: 'View Roles Audit Trail',
    englishLabel: 'View Roles Audit Trail',
    arabicLabel: null,
    useFlag: true,
    approveFlag: null,
    individualAccess: null,
    companyAccess: null,
    staffAccess: true,
    remarks: null,
  },
  {
    category: 'Service Provider Applications',
    functionDescription: 'View Service Provider Applications',
    englishLabel: 'View Service Provider Applications',
    arabicLabel: null,
    useFlag: true,
    approveFlag: null,
    individualAccess: null,
    companyAccess: null,
    staffAccess: true,
    remarks: null,
  },
  {
    category: 'Service Provider Applications',
    functionDescription: 'Export Applications',
    englishLabel: 'Export Applications',
    arabicLabel: null,
    useFlag: true,
    approveFlag: null,
    individualAccess: null,
    companyAccess: null,
    staffAccess: true,
    remarks: null,
  },
  {
    category: 'Service Provider Applications',
    functionDescription: 'View Applications Audit Trail',
    englishLabel: 'View Applications Audit Trail',
    arabicLabel: null,
    useFlag: true,
    approveFlag: null,
    individualAccess: null,
    companyAccess: null,
    staffAccess: true,
    remarks: null,
  },
  {
    category: 'Service Provider Applications',
    functionDescription: 'Approve / Decline Applications',
    englishLabel: 'Approve / Decline Applications',
    arabicLabel: null,
    useFlag: true,
    approveFlag: null,
    individualAccess: null,
    companyAccess: null,
    staffAccess: true,
    remarks: null,
  },
  {
    category: 'Services',
    functionDescription: 'Read',
    englishLabel: 'Read',
    arabicLabel: null,
    useFlag: true,
    approveFlag: null,
    individualAccess: null,
    companyAccess: null,
    staffAccess: true,
    remarks: null,
  },
  {
    category: 'Services',
    functionDescription: 'Create',
    englishLabel: 'Create',
    arabicLabel: null,
    useFlag: true,
    approveFlag: null,
    individualAccess: null,
    companyAccess: null,
    staffAccess: true,
    remarks: null,
  },
  {
    category: 'Services',
    functionDescription: 'Edit',
    englishLabel: 'Edit',
    arabicLabel: null,
    useFlag: true,
    approveFlag: null,
    individualAccess: null,
    companyAccess: null,
    staffAccess: true,
    remarks: null,
  },
  {
    category: 'Services',
    functionDescription: 'Delete',
    englishLabel: 'Delete',
    arabicLabel: null,
    useFlag: true,
    approveFlag: null,
    individualAccess: null,
    companyAccess: null,
    staffAccess: true,
    remarks: null,
  },
  {
    category: 'Services',
    functionDescription: 'Export',
    englishLabel: 'Export',
    arabicLabel: null,
    useFlag: true,
    approveFlag: null,
    individualAccess: null,
    companyAccess: null,
    staffAccess: true,
    remarks: null,
  },

  {
    category: 'Services',
    functionDescription: 'View Audit Trail',
    englishLabel: 'View Audit Trail',
    arabicLabel: null,
    useFlag: true,
    approveFlag: null,
    individualAccess: null,
    companyAccess: null,
    staffAccess: true,
    remarks: null,
  },
  {
    category: 'Services',
    functionDescription: 'Status "Deactivate / Reactivate"',
    englishLabel: 'Status "Deactivate / Reactivate"',
    arabicLabel: null,
    useFlag: true,
    approveFlag: null,
    individualAccess: null,
    companyAccess: null,
    staffAccess: true,
    remarks: null,
  },
  {
    category: 'Support Tickets',
    functionDescription: 'Read',
    englishLabel: 'Read',
    arabicLabel: null,
    useFlag: true,
    approveFlag: null,
    individualAccess: null,
    companyAccess: null,
    staffAccess: true,
    remarks: null,
  },
  {
    category: 'Support Tickets',
    functionDescription: 'Edit',
    englishLabel: 'Edit',
    arabicLabel: null,
    useFlag: true,
    approveFlag: null,
    individualAccess: null,
    companyAccess: null,
    staffAccess: true,
    remarks: null,
  },
  {
    category: 'Support Tickets',
    functionDescription: 'Export',
    englishLabel: 'Export',
    arabicLabel: null,
    useFlag: true,
    approveFlag: null,
    individualAccess: null,
    companyAccess: null,
    staffAccess: true,
    remarks: null,
  },

  {
    category: 'Support Tickets',
    functionDescription: 'Change Status "Open , Closed, etc"',
    englishLabel: 'Change Status "Open , Closed, etc"',
    arabicLabel: null,
    useFlag: true,
    approveFlag: null,
    individualAccess: null,
    companyAccess: null,
    staffAccess: true,
    remarks: null,
  },
  {
    category: 'Support Tickets',
    functionDescription: 'View Audit Trail',
    englishLabel: 'View Audit Trail',
    arabicLabel: null,
    useFlag: true,
    approveFlag: null,
    individualAccess: null,
    companyAccess: null,
    staffAccess: true,
    remarks: null,
  },
  {
    category: 'System Settings',
    functionDescription: 'View System Settings',
    englishLabel: 'View System Settings',
    arabicLabel: null,
    useFlag: true,
    approveFlag: null,
    individualAccess: null,
    companyAccess: null,
    staffAccess: true,
    remarks: null,
  },
  {
    category: 'System Settings',
    functionDescription: 'Edit System Settings',
    englishLabel: 'Edit System Settings',
    arabicLabel: null,
    useFlag: true,
    approveFlag: null,
    individualAccess: null,
    companyAccess: null,
    staffAccess: true,
    remarks: null,
  },
  {
    category: 'System Settings',
    functionDescription: 'View System Settings Audit Trail',
    englishLabel: 'View System Settings Audit Trail',
    arabicLabel: null,
    useFlag: true,
    approveFlag: null,
    individualAccess: null,
    companyAccess: null,
    staffAccess: true,
    remarks: null,
  },
  {
    category: 'User Management',
    functionDescription: 'Create Own User',
    englishLabel: 'Create User',
    arabicLabel: null,
    useFlag: true,
    approveFlag: true,
    individualAccess: 'No',
    companyAccess: true,
    staffAccess: true,
    remarks:
      'This is a feature to enable organizations to create their own users where user admin is allowed.',
  },
  {
    category: 'User Management',
    functionDescription: 'Edit Own User Details',
    englishLabel: 'Edit User',
    arabicLabel: null,
    useFlag: true,
    approveFlag: true,
    individualAccess: 'No',
    companyAccess: true,
    staffAccess: true,
    remarks: null,
  },
  {
    category: 'User Management',
    functionDescription: 'Delete Own User',
    englishLabel: 'Delete User',
    arabicLabel: null,
    useFlag: true,
    approveFlag: true,
    individualAccess: 'No',
    companyAccess: true,
    staffAccess: true,
    remarks: null,
  },

  {
    category: 'User Management',
    functionDescription: 'Edit Own User Status',
    englishLabel: 'Edit User Status',
    arabicLabel: null,
    useFlag: true,
    approveFlag: true,
    individualAccess: 'No',
    companyAccess: true,
    staffAccess: true,
    remarks:
      'This is a feature to enable organizations to edit the status of a user (e.g. Activated / Blocked / etc...)',
  },
  {
    category: 'User Management',
    functionDescription: 'Reset Password',
    englishLabel: 'Reset Password',
    arabicLabel: null,
    useFlag: true,
    approveFlag: 'N/A',
    individualAccess: null,
    companyAccess: null,
    staffAccess: true,
    remarks: null,
  },
  {
    category: 'User Management',
    functionDescription: 'View User Audit Trail',
    englishLabel: 'View User Audit Trail',
    arabicLabel: null,
    useFlag: true,
    approveFlag: 'N/A',
    individualAccess: 'No',
    companyAccess: 'No',
    staffAccess: true,
    remarks: null,
  },
  {
    category: 'User Management',
    functionDescription: 'Read "View" User information',
    englishLabel: 'View User',
    arabicLabel: null,
    useFlag: true,
    approveFlag: null,
    individualAccess: null,
    companyAccess: null,
    staffAccess: true,
    remarks: null,
  },
  {
    category: 'User Management',
    functionDescription: 'Export Users Information',
    englishLabel: 'Export Users Information',
    arabicLabel: null,
    useFlag: true,
    approveFlag: null,
    individualAccess: null,
    companyAccess: null,
    staffAccess: true,
    remarks: null,
  },
  {
    category: 'Workflow',
    functionDescription: 'Read',
    englishLabel: 'Read',
    arabicLabel: null,
    useFlag: true,
    approveFlag: null,
    individualAccess: null,
    companyAccess: null,
    staffAccess: true,
    remarks: null,
  },
  {
    category: 'Workflow',
    functionDescription: 'Create',
    englishLabel: 'Create',
    arabicLabel: null,
    useFlag: true,
    approveFlag: null,
    individualAccess: null,
    companyAccess: null,
    staffAccess: true,
    remarks: null,
  },
  {
    category: 'Workflow',
    functionDescription: 'Edit',
    englishLabel: 'Edit',
    arabicLabel: null,
    useFlag: true,
    approveFlag: null,
    individualAccess: null,
    companyAccess: null,
    staffAccess: true,
    remarks: null,
  },
  {
    category: 'Workflow',
    functionDescription: 'Delete',
    englishLabel: 'Delete',
    arabicLabel: null,
    useFlag: true,
    approveFlag: null,
    individualAccess: null,
    companyAccess: null,
    staffAccess: true,
    remarks: null,
  },
  {
    category: 'Workflow',
    functionDescription: 'Export',
    englishLabel: 'Export',
    arabicLabel: null,
    useFlag: true,
    approveFlag: null,
    individualAccess: null,
    companyAccess: null,
    staffAccess: true,
    remarks: null,
  },
  {
    category: 'Workflow',
    functionDescription: 'View Audit Trail',
    englishLabel: 'View Audit Trail',
    arabicLabel: null,
    useFlag: true,
    approveFlag: null,
    individualAccess: null,
    companyAccess: null,
    staffAccess: true,
    remarks: null,
  },
  {
    category: 'Workflow',
    functionDescription: 'Status "Deactivate / Reactivate"',
    englishLabel: 'Status "Deactivate / Reactivate"',
    arabicLabel: null,
    useFlag: true,
    approveFlag: null,
    individualAccess: null,
    companyAccess: null,
    staffAccess: true,
    remarks: null,
  },
  {
    category: 'Platform',
    functionDescription: 'Finalize request',
    englishLabel: 'Request finalizer',
    arabicLabel: 'المُصَفِّي الطَّلَب',
    useFlag: true,
    approveFlag: null,
    individualAccess: null,
    companyAccess: null,
    staffAccess: true,
    remarks: null,
  },
];
