export enum NotificationScopesEnum {
  CREATE_OFFER = 'Create Offer',
  UPDATE_OFFER = 'Update Offer',
  OFFER_RESPONSE = 'Offer Response',
  BIDS = 'Bids',
  RESULT = 'Results',
  LAST_MINUITE = 'Last minute',
  FIFTEEN_MINUITE_TOeND = '15 minutes to end',
  CREATED = 'Created',
  DELIVERED = 'Delivered',
  PRICE_CHANGE = 'Price change',
  UPCOMING_EVENTS = 'Upcoming Auctions',
  CREATE_INVOICE = 'Create Invoice',
  REGISTRATION = 'Registration',
  ACCEPTED = 'Accepted',
}
